### ISSUE TITLE
Graphcache not triggering rerender when a field goes from null to non-null

### ISSUE THREAD

**Issue by ostrebler** [FormidableLabs/urql#1878] opened 2021-08-21 20:10 UTC
urql version & exchanges: 2.0.4 (@urql/exchange-graphcache: 4.3.0)

**Steps to reproduce**

Imagine something simple like this : 

```graphql
  type Meal {
    id: ID!
    name: String!
  }

  type Entry {
    id: ID!
    name: String!
    meal: Meal
  }

  type EntryPage {
    total: Int!
    items: [Entry!]!
  }

  type Query {
    entries(): EntryPage!
  }

  type Mutation {
    editEntry(
      id: ID!
      name: String!
      meal: ID
    ): Entry!
  }
```

**Expected behavior**

When `editEntry` returns on the frontend, the data of `entries` should be updated via graphcache magic.

**Actual behavior**

It does not trigger an update when editing an `Entry` which had a `meal` field equal to `null` and now has that same field equal to some `Meal`. Every other edit triggers an update (`Meal` to different `Meal`, `Meal` to `null`, change on field `name`, etc.).

**Comment by kitten** [comment] 2021-08-21 20:50
I don't really see this as possible, given that it'd update the `Entry` and hence every query that contains a "path" to this `Entry` must update. Since this may involve other updates or even optimistic updates, I wouldn't exclude something else going on or an edge case being involved.

Either way, given that we likely won't take a look at this immediately given the investigation work needed to even confirm or reproduce this, I'd love to have a reproduction here ✌️

**Comment by ostrebler** [comment] 2021-08-21 20:56
@kitten I sadly don't have time to write a reproduction right now because I have to deliver this projet to a client on Monday. But I can guarantee there is no other update nor optimistic update, that's 100% sure. I'm trying to rollback versions now to see when this issue started.

**Comment by kitten** [comment] 2021-08-21 21:04
@ostrebler Fair enough! Have you tried dropping a `debugExchange` into your `exchanges` as the first item and checked that the query is going through? If so, we can also check whether it's properly causing either a cache miss or a result.

I'd say, if you find a prior version that doesn't cause this that may already be helpful enough, since we can then just check what's changed and see if it regressed this case

**Comment by ostrebler** [comment] 2021-08-21 21:11
Ok, I found something.

`urql` version 1.11.5 and `@urql/exchange-graphcache` version 3.3.4 don't trigger this problem, nor [the other one with the duplicate queries](https://github.com/FormidableLabs/urql/issues/1879). So that will be my quick fix for now. I hope that helps you!

**Comment by kitten** [comment] 2021-08-21 21:18
I may still need some information around which version of `@urql/core` you're using and whether that's the differentiating factor (if necessary, with yarn's resolutions that may be a quick way to test this). My hunch basically is that it's an edge case in `@urql/core`'s new single-source behaviour, which introduced some fixes but a new regression, which was then fixed in `@urql/core@2.2.0`. Basically, since `urql` is just a bindings package, I'm not entirely convinced it's causing any of this unless you're using suspense. So, with `@urql/core` potentially changing as you're downgrading that may have more to do with this.

Regarding, `@urql/exchange-graphcache`'s version, there was something regarding `cache.invalidate` that was fixed in `v3.4.0`, but since this directly addressed an issue like this, I see this as a bit unlikely, but possible. But since you're also having an issue without using `cache.invalidate` this may be unrelated entirely.

**Comment by ostrebler** [comment] 2021-08-21 21:23
I see. I don't know why but I have two `@urql/core` in my `yarn.lock`. One is 1.16.0, the other 2.3.0.

**Comment by kitten** [comment] 2021-08-21 21:27
That probably means you'll want to deduplicate them using a tool like `yarn-deduplicate` or similar. Generally, the one that you're using to create your client with (typically `urql`'s one or a top-level one) would take precedence, but `yarn list` will likely show you which one it's using as the top-level one.

I believe, #1300 together with #1859 may potentially be causing this edge case, but I'm not entirely sure yet. In that case, `@urql/core` should be unrelated, however, using the latest version (or one before the single-source change) should avoid you hitting a different bug that's already been fixed.

I'll close #1879 for now as a duplicate, since I think part of this behaviour will be down to the above `@urql/core` fix, and part to the regression I've mentioned

**Comment by ostrebler** [comment] 2021-08-21 21:40
Alright, please let me know if you need more informations. The `yarn list` gives me the following : 

```
├─ @urql/core@2.3.0
│  ├─ @graphql-typed-document-node/core@^3.1.0
│  └─ wonka@^4.0.14
├─ @urql/exchange-graphcache@3.3.4
│  ├─ @urql/core@>=1.16.1
│  └─ wonka@^4.0.14
...
├─ urql@1.11.5
│  ├─ @urql/core@^1.16.0
│  ├─ @urql/core@1.16.2
│  │  ├─ @graphql-typed-document-node/core@^3.1.0
│  │  └─ wonka@^4.0.14
│  └─ wonka@^4.0.14

```

**Comment by manojsethi** [comment] 2021-08-24 07:46
Happening same with me too. 

I have a query which returns null when a page loads then based on a mutation I am use cache.updateQuery in the graphCache Exchange. Upon checking the cache.readQuery in the exchange itself I can see that the new data is set but when the page over the page where the query needs to be executed with new value it returns null in the data.

```
    "graphql": "^15.5.1",
    "next": "latest",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "urql": "^2.0.4",
    "wonka": "^4.0.15"
```

FYI - I am just following the Ben Full Stack Tutorial. The cache updates correctly once the query has data and is not null. So it is something happening only if the data of a query is null.

**Comment by ostrebler** [comment] 2021-08-24 12:53
I honestly think this is a bug. I made a parallel with another big app I worked on a few weeks ago. I remember that some query updates (following cache invalidations) suddenly wouldn't happen anymore.

**Comment by kitten** [comment] 2021-08-24 19:30
Just sticking my investigation notes here for now, so they're kept around:

1. Spread copies data here into ownership: `{ ...data }` https://github.com/FormidableLabs/urql/blob/ab7ac600a05f49af3b4bb8430c970d125b317c55/exchanges/graphcache/src/store/data.ts#L78
2. That means this is then "owned" by this query run: https://github.com/FormidableLabs/urql/blob/ab7ac600a05f49af3b4bb8430c970d125b317c55/exchanges/graphcache/src/store/data.ts#L88-L89
3. Triggers the logic that skips fields that have previously been set to `null`, since it may copy `null` fields: https://github.com/FormidableLabs/urql/blob/ab7ac600a05f49af3b4bb8430c970d125b317c55/exchanges/graphcache/src/operations/query.ts#L567-L568

This is not that easy to fix, but very easy to pinpoint now.

Additionally, we'll also need to fix this line for an unrelated issue for which it'll be hard to write a test, since we lost the preconditions for it: https://github.com/FormidableLabs/urql/blob/ab7ac600a05f49af3b4bb8430c970d125b317c55/exchanges/graphcache/src/operations/query.ts#L69

**Closed** 2021-08-24 22:53 UTC
Labels: bug 🐛

**Comment by nandorojo** [comment] 2022-11-03 23:28
Anyone still seeing this bug with the following versions?

```
urql: 3.0.3
@urql/exchange-graphcache: 5.0.4
```

I notice that calling `cache.invalidate()` has some inconsistent behavior for me.

I'm trying to invalidate `myOrganizations` when `createOrganization` resolves. I can see in the network tab that `createOrganization` works properly. I also see the `console.log` below going through. However, a new request does _not_ go through for `myOrganizations`, even though there is indeed a hook mounted that is requesting `myOrganizations.

I can try to open a new issue with a repro if this seems totally unexpected. Just a bit hard to repro mutations.

```tsx
updates: {
  Mutation: { 
    createOrganization(parent, args, cache, info) {
     for (const field of cache.inspectFields('Query')) {
      if (field.fieldName == 'myOrganizations') {
        console.log('[urql][invalidateList]', field.fieldName, field.arguments)
        cache.invalidate('Query', field.fieldName, field.arguments)
      }
     }
    }, 
  },
},
```
