### ISSUE TITLE
info.partial not refetching query

### ISSUE THREAD

**Issue by manojsethi** [FormidableLabs/urql#1908] opened 2021-08-29 05:41 UTC
### Discussed in https://github.com/FormidableLabs/urql/discussions/1907

I can confirm this as an issue in the latest version because when I try it with version 4.2.1 it works fine but with the latest version 4.3.2 it is not working as expected. So would like to get it escalated. 

Hi, I am just following the ben awad tutorial and am kind of stuck at the moment at pagination. I am using the same cursor pagination and after using info.partial it is not hitting the server even if it is set to true. 

This doesn't work

```
export const cursorPagination = (): Resolver<any, any, any> => {
  return (_parent, fieldArgs, cache, info) => {
    const { parentKey: entityKey, fieldName } = info;

    const allFields = cache.inspectFields(entityKey);
    const fieldInfos = allFields.filter((info) => info.fieldName === fieldName);
    const size = fieldInfos.length;

    if (size === 0) {
      return undefined;
    }

    const isItInTheCache = cache.resolve(entityKey, `${fieldName}(${stringifyVariables(fieldArgs)})`);

    info.partial = !isItInTheCache;
    const results: string[] = [];
    fieldInfos.forEach((fi) => {
      const data = cache.resolve(entityKey, fi.fieldKey) as string[];
      results.push(...data);
    });

    return results;
  };
};
```

But this works

```
export const cursorPagination = (): Resolver<any, any, any> => {
  return (_parent, fieldArgs, cache, info) => {
    const { parentKey: entityKey, fieldName } = info;

    const allFields = cache.inspectFields(entityKey);
    const fieldInfos = allFields.filter((info) => info.fieldName === fieldName);
    const size = fieldInfos.length;

    if (size === 0) {
      return undefined;
    }

    const isItInTheCache = cache.resolve(entityKey, `${fieldName}(${stringifyVariables(fieldArgs)})`);
    //BELOW 3 LINES MAKE IT WORK BUT THERE IS NO EFFECT OF VALUE ON info.partial
    if (!isItInTheCache) {
      return undefined;
    }
    //info.partial = !isItInTheCache;
    const results: string[] = [];
    fieldInfos.forEach((fi) => {
      const data = cache.resolve(entityKey, fi.fieldKey) as string[];
      results.push(...data);
    });

    return results;
  };
};
```

Can somebody guide me if I am doing wrong something or if @kitten or @JoviDeCroock you can look into it if it sounds like a bug to you?

**Comment by frederikhors** [comment] 2021-08-29 07:07
Maybe related to https://github.com/FormidableLabs/urql/issues/1904?

**Comment by manojsethi** [comment] 2021-08-29 07:21
@frederikhors well I am not sure but I am not using that policy, I am using the default **cache-first** policy.

**Comment by kitten** [comment] 2021-08-30 09:38
@frederikhors I think you could be right. When `ctx.partial` is set it triggers the same code path as `cache-and-network` does, which means that the `dedupExchange` triggers.

@manojsethi: I can't quite do a lot to confirm this as there's no reproduction here, but you could try removing the `dedupExchange`. If it starts working that'd confirm @frederikhors' assumption here.

So in short, if you have a `createClient({ exchanges: [dedupExchange, cacheExchange({}), fetchExchange] })` setup, then try removing the `dedupExchange` from that list please! ❤️ Once we've shipped the fix you'll then be able to put it back.

**Comment by manojsethi** [comment] 2021-08-30 11:48
Hi @kitten,  I tried as per your suggestion and it works fine when I remove the dedupExchange so that confirms it's a bug. It's a nice learning experience for me to know how things are working behind the scene. I am attaching the sample code along with the test data for replication if that helps.
[Issue_Replication.zip](https://github.com/FormidableLabs/urql/files/7076434/Issue_Replication.zip)

**Comment by kitten** [comment] 2021-08-30 11:51
@manojsethi That's awesome! Then this is indeed a duplicate of #1904 and we can close this since the fix for it should be effective ✨👏

**Closed by kitten** 2021-08-30 11:51 UTC
