### ISSUE TITLE
Better packaging for non React consumers

### ISSUE THREAD

**Issue by tchak** [FormidableLabs/urql#253] opened 2019-06-03 19:38 UTC
I am working on `Ember.js` addon for `urql`. It would make my life easier (and I suspect of any implementor not using `React` stuff) to have a separate package with core API.

**Comment by tchak** [comment] 2019-06-03 19:39
Or at least provide a standalone build with no references to `React`.

**Comment by kitten** [comment] 2019-06-04 21:48
So, this is a tricky one. While we've built urql so that no parts of React or parts of our logic blend into one another we would like to keep the amount of libraries we publish as low as possible; at least for the time being and probably not forever.

So this is definitely something we'll consider if other libraries for different UI frameworks become popular.

For now though tree shaking should be able to remove all parts of the urql code that you don't use. So kind of controversial, but you could bundle urql into your own library without actually depending on it 🤔

**Comment by kitten** [comment] 2019-09-10 00:23
I'll close this as a duplicate of https://github.com/FormidableLabs/urql/issues/423 which is a concrete RFC on how we're going to move forward with this without introducing another package :+1:

**Closed by kitten** 2019-09-10 00:23 UTC
Labels: question 🙋
