### ISSUE TITLE
__typename disappeared upon cache read of array query

### ISSUE THREAD

**Issue by hoangvvo** [FormidableLabs/urql#1268] opened 2021-01-03 05:00 UTC
Happy New Year!

When reading a query of array from cache (either using `client.readQuery` or on component remount), `__typename` is disappeared.

urql version & exchanges: 

```
"urql": "^1.11.4"
"@urql/exchange-graphcache": "^3.3.3",
```

**Steps to reproduce**

https://github.com/hoangvvo/urql-array-query-bug

`__typename` should not dissapear.

**Actual behavior**

![urql array bug](https://user-images.githubusercontent.com/40987398/103472039-4a0fae80-4d56-11eb-8d99-1723d2039383.gif)

**Comment by hoangvvo** [comment] 2021-01-03 07:37
https://github.com/FormidableLabs/urql/discussions/1241

I just found this, and it seems like `__typename` *may* not be returned sometimes unless specifically requested. It does seem to be a bit of incosistency.

However the problem arises when dealing with a query of array of union/interface, where the cache gets "corrupted": fields from another object gets injected into another. I will try to add a reproduction to describe this better later.

**Comment by JoviDeCroock** [comment] 2021-01-03 09:18
Hey, what made you close this issue?

**Comment by sheldonbaker** [comment] 2021-09-30 07:45
I got bit by this today, FYI. Seems to be unexpected behaviour.

**Comment by hoangvvo** [comment] 2021-09-30 12:29
> I got bit by this today, FYI. Seems to be unexpected behaviour.

I agree, I think it should either always be omitted or present. Did cause me quite some time back then :D

**Comment by kitten** [comment] 2021-09-30 12:50
There's more details on this issue here: https://github.com/FormidableLabs/urql/issues/1366
But apart from that there've been several duplicates (and I believe, some threads in discussions re. this) ❤️

**Closed by kitten** 2021-09-30 12:50 UTC
Labels: bug 🐛
