### ISSUE TITLE
Pausing Queries with Svelte differs from docs

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#2195] opened 2022-01-13 15:59 UTC
I'm using `"@urql/svelte": "1.3.3"`.

For the first time today I tried to use `pause` like described https://formidable.com/open-source/urql/docs/basics/svelte/#pausing-queries.

```svelte
<script>
  import { operationStore, query } from '@urql/svelte';

  const todo = operationStore(
    `
    query {
      todo {
        id
        title
      }
    }`,
    undefined,
    { pause: true }
  );

  query(todo);

  function unpause() {
    $todo.context.pause = false;
  }
</script>

<button on:click="{unpause}">Unpause</button>
```

The code in this example doesn't work.

It only works if I add the line

```js
todos.reexecute();
```

in the `unpause()` function.

Is the docs wrong or `@urql/svelte`?

**Comment by max-las** [comment] 2022-01-30 17:30
I can confirm this. Using svelte bindings, setting $store.context.pause to false will not make the query continue. The reexecute() method must also be triggered on the store to get a query to run again after a pause. Not sure if this is intended, but it's definitely not explained in the docs.

**Comment by max-las** [comment] 2022-01-31 08:59
Actually, in accordance with the [Reexecuting Queries](https://formidable.com/open-source/urql/docs/basics/svelte/#reexecuting-queries) section of the docs, both the following work :
```javascript
$todos.context = { pause: false };
```
```javascript
todos.reexecute({ pause: false });
```
But this doesn't work
```javascript
$todos.context.pause = false;
```
Therefore the sample provided in [Pausing Queries](https://formidable.com/open-source/urql/docs/basics/svelte/#pausing-queries) is slightly wrong. The working version would be :
```javascript
<script>
  import { operationStore, query } from '@urql/svelte';

  const todo = operationStore(
    `
    query {
      todo {
        id
        title
      }
    }`,
    undefined,
    { pause: true }
  );

  query(todo);

  function unpause() {
    $todo.context = { pause: false };
  }
</script>

<button on:click="{unpause}">Unpause</button>
```
```diff
function unpause() {
-  $todo.context.pause = false;
+  $todo.context = { pause: false };
}
```

**Comment by kitten** [comment] 2022-02-02 23:24
Closing as duplicate of #2080
We're aware that this isn't working, but I'm still trying to get the energy that is frankly required to work on Svelte library code

**Closed by kitten** 2022-02-02 23:24 UTC
Labels: bug 🐛

**Comment by frederikhors** [comment] 2022-02-04 19:41
As you can see (from questions in discussions and issues) many people are working with Svelte.

Urql and Svelte together are an atomic bomb but death does not explode: happiness explodes! 😄

Can I ask you - with sincere curiosity, no judgment - why do you feel that working with Svelte requires more sacrifice than React?

_I asked the question because I have always learned something from you, and I hope in this case too._

**Comment by kitten** [comment] 2022-02-04 22:10
Oh, don't get me wrong. React has caused us a lot of sweat and tears with its several, neigh uncountable requirements to support Strict Mode, Suspense, React Concurrent, React 18 v prior versions, SSR, etc, etc. There are a lot of subtleties to getting that right. However, we know what kind of API we want from it, and the hooks API has been stable for a long time.

Comparatively, it's extremely hard to reason about a "good" API with Svelte that works for us. In fact, I'm not happy at all with our current API in `@urql/svelte`. As a non-Svelte developer, it's hard for me to tell whether it's objectively good, bad, meh, or okay. Maybe it's all of these at the same time 🤡
The fact of the matter is that while Svelte is a reactivity-first UI framework, its library tooling and internal API doesn't behave as such at all. In fact, I feel beyond some built-in primitives for async/await it's awkward at best at handling _changing_ data and a more flexible definition of work that's in progress beyond promises, which are (if lazy) either idle, pending, resolved, or rejected, whereas with any reactive model you're at least going through all of these repeatedly or can be in two states at the same time.

The reason why this is tricky for us is simple. We don't work with Svelte outside of the `urql` repo. We made bindings for Vue and Svelte, the former being a lot more obvious (Those are also admittedly used by less people), but we aren't comfortable with either anyway. So, again, all we can say is: making `@urql/vue` wasn't as hard (also take that with a grain of salt. We got core team support when making them)
That said, the API was very aware of reactivity _and_ pending/loading states at the same time. Something that may not even be as easy in React.

I'm splitting hairs here though. We ultimately have two problems:
- We're at our limit in the amount of code we can effectively maintain in a timely manner — while Vue and Svelte are pushing our comfort zone a little already
- Since we don't have anyone in the Svelte/Vue communities/core teams to actively maintain this with us (which obviously wouldn't be fair, isn't anyone's/their priority, and we aren't asking of them), that does mean we see it as a chore, and it isn't at the top of our list 😅

So, while `@urql/svelte` is growing by the rather imperfect measure of downloads, we're still prioritising `urql` (aka `react-urql`)
