### ISSUE TITLE
Cache updates/invalidation don't seem to work with @urql/svelte v2

### ISSUE THREAD

**Issue by Nickersoft** [FormidableLabs/urql#2508] opened 2022-06-18 18:44 UTC
This is an issue I've encountered in a personal project of mine that I've been able to reproduce in a separate repo. Cache invalidation and updating doesn't seem to be working with the new @urql/svelte package, as calls to `cache.invalidate()` and `cache.updateQuery()` that were working before for me now produce no updates in my UI _or_ within the URQL devtools.

urql version & exchanges:

`@urql/core`: 2.5.0
`@urql/exchange-graphcache`: 4.4.3
`@urql/svelte`: 2.0.1

**Steps to reproduce**

I have a reproduction repo [available here](https://github.com/Nickersoft/urql-example/). All you have to do is clone, run `npm install`, run `npm dev`, then click the button in the UI. The SWAPI API doesn't support mutations, so I wrote a local query resolver that manually updates the cache but results in no changes to the UI.

**Expected behavior**

I'd expect cache updates to be reflected in the UI as they have previously.

**Actual behavior**

Nothing happens.

**Comment by kitten** [comment] 2022-06-18 18:47
Duplicate of #2473

**Closed** 2022-06-18 18:48 UTC
Labels: bug 🐛

**Comment by Nickersoft** [comment] 2022-06-18 22:39
Thanks for the quick reply @kitten! I saw the other issue, but wasn't sure if that issue was stemming from a subscriptions-specific web socket issue, or if it was an issue with cache interactivity. Good to know it's the latter! Will keep my eye out over there.

I guess in the meantime the best choice is to downgrade, sadly :/
