### ISSUE TITLE
refetch does not issue new query unless requestPolicy is network-only

### ISSUE THREAD

**Issue by Cooke** [FormidableLabs/urql#299] opened 2019-06-13 13:23 UTC
I was expecting the "refetch" func returned from useQuery(...) to issue a new query at least when the requestPolicy is "cache-and-network" but that does not happen. Only when 'network-only' is set a new query will be issued.

**Comment by kitten** [comment] 2019-06-13 14:29
We have a test that covers this and it shouldn't make a difference when it's issued. No matter where you pass this policy. It will first serve you the cached result but then also issue an operation for a network request.

This behaviour is intentional but when you want to explicitly refetch `network-only` is in fact the right choice.

It is the only request policy that guarantees that a request will be sent immediately.

If you're seeing no network request on `cache-and-network` that might be an actual issue, although I wouldn't recommend this for refetching. But you'll have to check whether it wasn't just cancelled due to a change on the hook.

Either way a reproduction would be extremely helpful as we're otherwise just going after a vague description of a potential big which can be very time consuming 😅 Cheers!

**Comment by Ericnr** [comment] 2019-06-14 05:46
Just ran into the exact same problem. I have 
```js
const [{data, fetching, error}, executeQuery] = useQuery({
    query: GET_USERS,
    requestPolicy: "cache-and-network",
    variables: {query}
})
```
and when I click 
```js
<button onClick={() => executeQuery()} />
```
no request seems to be sent at all, it works when I set `executeQuery({ requestPolicy: "network-only" })`

**Comment by Cooke** [comment] 2019-06-14 11:45
@kitten Sorry for not trying very hard to make a reproducible. Though I tried at least a minute but failed with: https://github.com/FormidableLabs/urql/issues/302 . Would be cool if someone prepared a jsfiddler "app" with urql where reproducables could be created.

Refetching with "network-only" like @Ericnr suggests solves my problem, though I think it still is a bug. Also I think the API is a bit unexpected, that you have to explicitly instruct refetch to "refetch" but perhaps there are other use-cases which I haven't considered.

**Comment by kitten** [comment] 2019-06-14 12:27
@Cooke you probably forgot to run yarn in the root of the repository and we'll likely set up CodeSandboxes soon.

I'll see later whether I can find some time to take a closer look at this; This function is also not an explicit "refetch" function. We always (try; maybe we've missed a place) to refer to it as `executeQuery` since it's not for refetching but dispatching another operation.

I'm also pretty sure we have a section in the docs that's pretty clear on this 😅

- https://github.com/FormidableLabs/urql/blob/master/docs/getting-started.md
- https://github.com/FormidableLabs/urql/blob/master/docs/basics.md#request-policies

> Next, we can take a look at how to use 'network-only' to force a refetch imperatively. In our previous example this would come in handy to refresh the list of todos.

I'd love to know whether these sections could be expanded upon.

Regardless, I'll check whether it behaves as intended. Maybe we'll also need to revise the docs.

**Comment by Cooke** [comment] 2019-06-15 14:48
@kitten even if I was surprised by the need for "network-only" you are correct that docs are clear on the re-fetch technique. Still a bug with "cache-and-network" though.

**Comment by matheus-rosin** [comment] 2019-07-15 17:06
@Cooke I was facing this today, in that if I have an `useQuery` with `cache-and-network` request policy which firstly returned nothing, even when I imperatively called `executeQuery` it was not being sent (checked in Chrome dev tools network tab). What I figured out is that `executeQuery` accepts an `OperationContext`, so I tried:

```javascript
executeQuery({
  requestPolicy: 'network-only',
});
```

and it worked! 🎉 
Maybe it can help :)

**Comment by kitten** [comment] 2019-07-23 09:24
I'll close this for now in favour of #345 since that issue has more information and updates on the underlying bug :)

**Closed by kitten** 2019-07-23 09:24 UTC
Labels: needs more info :raised_hand_with_fingers_splayed:
