### ISSUE TITLE
[@urql/exchange-execute] Async Context Provider

### ISSUE THREAD

**Issue by shtse8** [FormidableLabs/urql#2581] opened 2022-07-29 07:54 UTC
Some context value needs to be provided in async. currently, exchange execute only support sync context. it should be apollo `SchemaLink` equivalent.

### apollo client (works perfect)
```ts
const schemaLink = new SchemaLink({
        schema,
        context: async () => {
         const value = await readConfig()
         return {
             value: value
         }
        },
      })
```

### urql
```ts
executeExchange({
        schema,
        // failed for async
        context: async () => {
         const value = await readConfig()
         return {
             value: value
         }
        },
      }),
```

**Comment by kitten** [comment] 2022-07-29 08:47
Duplicate of #2406

**Closed** 2022-07-29 08:47 UTC
Labels: future 🔮
