### ISSUE TITLE
Add a way to fetchMore and merge results (pagination / infinite scrolling)

### ISSUE THREAD

**Issue by jrobber** [FormidableLabs/urql#201] opened 2019-02-23 20:46 UTC
First, super neat library.  Great to see something less bloated out there.  

It would be great if it worked a little closer to Apollo's Query component and allowed the ability to fetchMore.  The executeQuery function provided by the Query callback is fine for refreshing, but is insufficient for infinite scroll scenarios.

**Comment by kitten** [comment] 2019-02-23 20:54
This will be out-of-scope for urql itself but I'm working on a normalised cache that will be a drop-in replacement for the built-in document cache.

It's going to be a little different from Apollo's approach, but will be as seamless as changing variables and expecting a full list for instance ✨

**Comment by jrobber** [comment] 2019-02-23 20:59
Thanks for the quick response.  I'll do that for now.

**Comment by kitten** [comment] 2019-02-23 21:02
@jrobber Let me know if you need any help! The current urql package will likely not include this, but it'd be great to start a "recipes" docs section that explains such an approach.

I'd suspect that even with a normalised cache, some would still love to opt-in to the more basic approaches for the sake of bundlesize and simplicity

**Comment by jrobber** [comment] 2019-02-23 23:19
I got something simple working by adding an intermediary component between the query and my component that merges the value in componentWillRecieveProps, but I don't feel like it's going to be a very good recipe.  Adding an extra component to store and merge data adds a lot of extra props passing just to achieve the basic scenario for fetching more pages.  It also requires that once you render the intermediary component that you have to ensure it stays loaded or you lose your aggregated data array.

It's quite possible someone smarter than me could do it better/cleaner.  But as long as the only hook into getting query results is in the render callback we won't be able to store or modify data on the same component (can't update state from render method).  Meaning we have to insert an intermediate, and that makes things messy.

**Comment by kitten** [comment] 2019-02-26 02:17
@andyrichardson has picked this up and we're looking to provide:

- A preferable, simple API that also works with the document cache that knows how to "fetchMore" and "merge results". This API might be built into `useQuery` or a separate hook, but will be very similar to Apollo's `fetchMore`
- A built-in way to merge pages of a paginated field into one list in the normalised cache that I'm working on

**Comment by rafamel** [comment] 2019-05-28 10:56
Hi @kitten, just wondering whether the new cache is still being actively worked on?

**Comment by kitten** [comment] 2019-05-28 11:14
@rafamel it is indeed but I haven't had much time recently. I'll see whether I can get it done next week. You can follow its development here: https://github.com/kitten/urql-exchange-graphcache

**Comment by rafamel** [comment] 2019-05-29 14:04
@kitten That's great news. I'm willing to bet on `urql` if that's on the near roadmap. I love the minimal core philosophy and the exchanges-based architecture. It's easily extensible and getting a grasp of what goes on behind the scenes is fairly simple. It does lack a few key features but I believe between the new cache and some minimal investment on exchanges development this can be all powerful :D. It would be great to have a section on the docs to list recommended externally developed exchanges for certain features, as they come. I'm personally planning of getting some going.

**Comment by stearm** [comment] 2019-08-06 10:24
@kitten any news about this topic? :)

**Comment by JoviDeCroock** [comment] 2019-08-06 15:29
@stearm work is being done on the graphcache, we're putting a lot of thought into this so we can get it right. This would solve the pagination issue

**Comment by stearm** [comment] 2019-08-06 20:47
Amazing! Thank you, I would like to be helpful if possible, do you have any topic in which I can give a contribution?

**Comment by JoviDeCroock** [comment] 2019-08-22 07:26
Hey,

While testing our new (graphCache)[https://github.com/FormidableLabs/urql-exchange-graphcache] with a real-world application I encountered this issue.

Maybe the solution used there can help you out:

```
import React from 'react';
import { useQuery } from 'urql';

const usePreviousValue = (track) => {
  const ref = React.useRef(track);
  React.useEffect(() => {
    ref.current = track;
  });
  return ref.current;
}

const usePagination = (query, keyword, limit = 20, initialFrom) => {
  const [result, setResult] = React.useState([]);
  const [from, setFrom] = React.useState(initialFrom);

  const [{ fetching, data, error }] = useQuery({
    query,
    variables: { limit, from },
  });

  const prevFetching = usePreviousValue(fetching);

  React.useEffect(() => {
    if (prevFetching === true && fetching === false && !error) {
      setResult(d => [...d, ...data[keyword]);
    }
  }, [fetching, prevFetching, data, error]);

  const fetchMore = React.useCallback(() => {
    setFrom(s => s + limit);
  }, [limit]);

  return [{ data: result, error }, fetchMore, data && data.hasMore];
}

export default usePagination;
```

**Comment by kitten** [comment] 2019-08-22 12:35
So as @JoviDeCroock is saying, there's basically two solutions that we think are sufficient to be able to close this issue:

- Implementing a `usePagination` hook or a component for pages being infinitely appended
- Use `@urql/exchange-graphcache` and create a resolver & page updater like what you can do with Apollo

I think either solutions aren't necessarily patterns that we'd build in, but there'll be more guides around both! For now I'll close this issue. Happy to answer any questions about this on Spectrum though :) spectrum.chat/urql

**Closed by kitten** 2019-08-22 12:35 UTC
Labels: feature 🚀, future 🔮

**Comment by JoviDeCroock** [comment] 2020-01-20 13:45
@ivan-kleshnin we now have an out of the box solution if you are using [graphcache](https://github.com/FormidableLabs/urql-exchange-graphcache/blob/master/docs/resolvers.md#simple)

**Comment by ivan-kleshnin** [comment] 2020-01-20 13:52
Yeah. But document-based cache was a selling point of URQL to me (and other GraphQL newbies I guess)! We should have some recipes for it as well. I've grown to hate ApolloClient because of state links and code spaghetties dedicated to cache updates.

**Comment by roshangm1** [comment] 2020-01-30 08:12
> @ivan-kleshnin we now have an out of the box solution if you are using [graphcache](https://github.com/FormidableLabs/urql-exchange-graphcache/blob/master/docs/resolvers.md#simple)

Do you have working example for simple pagination ?

**Comment by ivan-kleshnin** [comment] 2020-01-30 08:52
Yes. But I'm most probably switching to Apollo-Client so I don't care about publishing it.

**Comment by roshangm1** [comment] 2020-01-30 08:55
> Yes. But I'm most probably switching back to Apollo-Client so I don't care about publishing it.

You can at least publish the gist somewhere so that it would help other people who is using this library instead. What is the main reason of switching back to apollo for you ?

**Comment by ivan-kleshnin** [comment] 2020-01-30 10:11
> ou can at least publish the gist somewhere so that it would help other people who is using this library instead.

I'll see if that's possible.

> What is the main reason of switching back to apollo for you?

Not enough information available: docs, examples, searchable questions and answers. 
I work with GraphQL alone at my projects and I don't have enough time (or health for that matter) to lurk through such big code bases. Apollo 3.0 looks more similar to URQL, by the way – the are picking up some good design decisions.

Neverthelles, I keep tracking the progress of this project. Pretty sure, I'll reconsider this once again in the future.

**Comment by JoviDeCroock** [comment] 2020-01-30 10:20
Hey @ivan-kleshnin 

I'm sorry to hear that, if you got any pointers as to what parts of the docs we can improve, what kind of examples you want to see those would be more than welcome. This way we can improve for these in the future.

**Comment by ivan-kleshnin** [comment] 2020-01-30 11:10
https://blog.logrocket.com/exploring-urql-from-an-apollo-perspective/

> Apollo has a lot of API that urql does not. For example, Apollo gives you direct access to the cache. That can be really useful if you are working against a GraphQL schema that does not return the types needed for cache invalidation.

For example ^ this. I've found I sometimes really need a direct cache access and I don't even know if URQL allows it.

Most of the current docs is centered around streams and library extensions which a casual user exploring the possibilities of the library is probably not really into.

**Comment by Miloshinjo** [comment] 2021-01-13 15:56
Hello, is there an example of infinite-scrolling implementation in React with `relayPagination`? I have set it up, but I have no clue how to trigger "fetchMore" in order to concatinate the results and have them all show up (based on some trigger). Is there a working example? 

I saw a tweet from Ben Awad about this and his solution, but I am wondering if that is directly opposite to what you have out of the box.

Thanks

**Comment by kitten** [comment] 2021-01-13 16:17
@Miloshinjo the example that Ben Awad has tweeted is our advise on what to do when your API needs to either often invalidate, update, or chunk pages and doesn't need a single, "infinitely"-merged array of items.

So `relayPagination` is an out-of-the-box solution that is easier to set up and use. To fetch more data you'll have to update the variables to the next page and the resolver will merge it with prior ones automatically.

**Comment by Miloshinjo** [comment] 2021-01-13 16:28
Firstly, thank you for the quick response. 

I am stuck on "fetching more data" since whenever i update variables (let's say my limit or first is 2), I always get 2 results (new ones), but my old ones are removed. I am perhaps setting this up all wrong. 

I am building a slack-like app, where I want to scroll up and see older results and I am trying to achieve it via pagination. (atm I am testing it with a Load More button, but whenever i press it, I just get 2 new results, old ones are replaced). That's what Im trying to figure out :) how to call load more without "old results" being replaced by new, but concatinated on them :) 

I am keeping variables in react state and just updating them via state which is causing component to rerender (limit stays the same - 2). Is there any example that you have that has worked for you on the UI side or shall I keep looking? :)

Sorry if I confused you or wasted your time, I've been stuck on this for 5-6 days :)

**Comment by kitten** [comment] 2021-01-13 17:00
@Miloshinjo have you checked whether the `relayPagination()` resolver is indeed on the correct field that returns the Relay pagination result?

**Comment by Miloshinjo** [comment] 2021-01-13 17:06
I will check that. Tho my result is `edges` and `pageInfo` top level `node` is inside the edges. 
What I am looking for is something akin to `fetchMore` like apollo has. I guess I don't know how to trigger that. But, if you say that this should work with normal state change, then I will check how the response looks again.

eg. I am getting `messages` so my response is `data.messages.edges` and `data.messages,pageInfo` :) 

Again, I will not bother you much with this, its at least good to know that this should work out of the box, so I will look again what I was missing :) 

Also, I very much appreciate your help.

**Comment by kitten** [comment] 2021-01-13 17:10
@Miloshinjo No worries! It sounds like you'll need to pass `{ resolvers: { Query: { messages: relayPagination() } } }` to Graphcache. The `nodes` rather than `edges` field is actually supported by it. Re: `fetchMore`; that's really an Apollo-ism, but our pattern is that the normalised cache data in Graphcache _always_ stays as true to server-data as possible and we're encouraging updates/resolvers/optimistic updates etc to be written so that they reflect what the server would give you. Hence `relayPagination` is an exception that just quickly enables infinite scrolling, but in other cases something like `fetchMore` is a tool we see as obsolete or unnecessary indirection, since components and fragments can also be used to merge data.

**Comment by Miloshinjo** [comment] 2021-01-13 17:13
@kitten I do have resolvers set up like that :) 

```const resolvers: ResolverConfig = {
  Query: {
    messages: relayPagination(),
  },
};```

I will see if backend can do me a solid and change from `edges` to `nodes` 

This is my query , posting it here just so if u notice something bad :)

```query Messages($first: Int, $after: ID) {
  messages(
    paginationOptions: { first: $first, after: $after }
  ) {
		edges {
      node {
        ...on Message {
          ...MessageFeed
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
      startCursor
      hasPreviousPage
    }
  }
}
```

**Comment by kitten** [comment] 2021-01-13 17:16
@Miloshinjo So that `paginationOptions` argument isn't spec-compliant with Relay pagination, so I'd advise you to either flatten that so it'll be compliant or to do `const messages = relayPagination()` and then to call that in your own resolver that maps over the arguments to it, e.g. `(parent, args, cache, info) => messages(parent, { ...args.paginationOptions }, cache, info);`

**Comment by Miloshinjo** [comment] 2021-01-13 18:04
Ohhhhhh, that's a big thing I missed. Thank you, i will check this out and test it. Thank you very much. Such small things missed can waste us days :) 

Best,
Milos

**Comment by Miloshinjo** [comment] 2021-01-15 11:50
@kitten Hey Phil, just wanna say thanks again, your suggestions did it and it's working as intended with a simple state change :) Best of luck to you.

**Comment by deadcoder0904** [comment] 2021-04-18 10:45
> I am building a slack-like app, where I want to scroll up and see older results and I am trying to achieve it via pagination. (atm I am testing it with a Load More button, but whenever i press it, I just get 2 new results, old ones are replaced). That's what Im trying to figure out :) how to call load more without "old results" being replaced by new, but concatinated on them :)

@Miloshinjo I'm facing the same issue currently → https://github.com/FormidableLabs/urql/discussions/1550

Can you post your code-block here so I can take a peek? I don't think I need a backend side of it, just the URQL frontend

**Comment by Miloshinjo** [comment] 2021-06-22 07:21
@deadcoder0904 Sorry for the late reply, I didn't even see this. I'm using `relayPagination` function from urql and backend adheres to that so we get all concatinated in the cache (Which has its pros AND cons) :)

**Comment by deadcoder0904** [comment] 2021-06-22 09:01
@Miloshinjo np, i figured it out already (i think) :)
