### ISSUE TITLE
Add ssrMode (suspense like support) and execute query with support for immediate results

### ISSUE THREAD

**Issue by Jokcy** [FormidableLabs/urql#208] opened 2019-03-11 10:25 UTC
At first mount, cDM will trigger anyway, so why not set fetching to true when Initialization. In my case, I just want to wait util the query finish then first render the children.

And useEffect is async, when using hooks, the default view may show on first render.

Also it's confusing at first we got no fetching and no error but data is undefined.

Is there any reason we need to set it false at first?

**Comment by kitten** [comment] 2019-03-11 11:46
Yes, this might become important because of how we're planning to integrate suspense, since we'll make this fetching logic a synchronous call then that may throw a promise.

Currently we can't tell whether we initially have some data, until we actually make the call which might then either come back synchronously or concurrently.

If we set fetching to true immediately as is, if you're relying on data when fetching is true, then you'll likely write code that'll also have to check whether data is undefined, which is suboptimal.

I haven't found a nice compromise for this yet withiut suspense tbh, but open to suggestions of course 👍

**Comment by reverie** [comment] 2019-03-11 18:48
@kitten So are the docs inaccurate? Sorry if I'm misunderstanding. But the docs seem to e.g. render a `TodoList` from `data` after only checking `fetching`. Don't you always have to check whether `data` is `undefined` first as well? If so the docs should be updated because this is confusing.

**Comment by Jokcy** [comment] 2019-03-12 03:12
So the main problem is that we won't know if the query we are fetching will return data synchronous (from cache for example) or not? 

Is it ok if we invoke `executeQuery ` in every render instead of in useEffect. Maybe some code like this will work:

```js
const executeQuery = useMemo(
  () => {
    let callbacked = false
    return (opts?: Partial<OperationContext>) => {
      if (!callbacked) {
        callbacked = true
        unsubscribe();
        setState(s => ({ ...s, fetching: true }));
    
        const [teardown] = pipe(
          client.executeQuery(request, {
            requestPolicy: args.requestPolicy,
            ...opts,
          }),
          subscribe(({ data, error }) =>
            setState({ fetching: false, data, error })
          )
        );
    
        unsubscribe = teardown
      }
    }
  },
  [request.key]
);

executeQuery()
```

If `subscribe` trigger synchronously when we already have data in this query, it will be same whether if  we set fetching to true or false.

**Comment by jlkiri** [comment] 2019-03-12 04:58
The docs seem to be inaccurate, because even after `fetching` becomes `false` , `data` is still `undefined` (so additional check is needed). Current workaround is to only check for data like

```javascript
if (!data) return <p>Loading...</p>
```

**Comment by kitten** [comment] 2019-03-12 11:16
@Jokcy Yea, that's probably what I'll implement although the unsubscribe might still have to live in useeffect's return. I'll check

@jlkiri Setting fetching to true initially is precisely what prevents you from having to check both right now. If data is undefined in your result you mightve received an error though

**Comment by jlkiri** [comment] 2019-03-12 14:14
I have a component like the one below. I already made sure that the data returned from the server is not `undefined`. If I drop the `data` check the component crashes because `data` is `undefined`, but **with** this guard, `data` is successfully rendered on the next render. So I just wanted to know whether it is a feature or a bug?

```javascript
function Home() {
  const [{ fetching, data, error }] = useQuery({ query: _bigQuery });

  if (fetching) return <div>Loading...</div>;
  if (!data) return <div>Still loading???</div>;

  return <div>{data.foo.bar}</div>
}
```

**Comment by Jokcy** [comment] 2019-03-13 01:31
@kitten I'd like to do some contribution, is there any way I can contribute?

**Comment by kitten** [comment] 2019-03-13 02:16
@Jokcy Yes of course! If you'd like to find a better implementation for the `useQuery` state that'd be great :+1: Me and @andyrichardson are here to help and we do have a `CONTRIBUTING.md`.

The gist of it is that in `useQuery` we create the `request` and check `request.key` for changes. We call and subscribe to `executeQuery` which also gives us a teardown function to cancel ongoing requests when needed.

This `executeQuery` subscription can theoretically be done outside of an effect. We can then check whether we got back a result synchronously. If not, it'd have to call `setState` somehow. We also need to ensure that the function that is returned from the hook can also be called and that on unmount the teardown is called 🤔 

@jlkiri Yes, sorry, I've been confusing myself. Tbh @andyrichardson wrote most of the hook so I got the `fetching` state the wrong way around. We'll have to fix this properly so that a `data === undefined` check becomes unnecessary by making sure that synchronous initial state is provided :+1:

**Comment by jlkiri** [comment] 2019-03-13 05:26
@kitten Thank you!

**Comment by Jokcy** [comment] 2019-03-13 08:11
@kitten em... it is dependent on wonka, which I'm not quite understand how it works. And there is no doc now (working on), also it being written in Reason which I never used. Maybe it's better I just giving some advice now .🤔

**Comment by kitten** [comment] 2019-06-03 16:13
Closing as a duplicate of #218 that has more comments/updates on the status

**Closed by kitten** 2019-06-03 16:13 UTC
Labels: feature 🚀
