### ISSUE TITLE
staleWhileRevalidate does not cause a new network request

### ISSUE THREAD

**Issue by yoshiwarab** [FormidableLabs/urql#2588] opened 2022-08-04 23:47 UTC
### Describe the bug

This is a very similar issue to https://github.com/FormidableLabs/urql/issues/2059.  It appears the same exact behavior is not present as the data is not falsely marked as not stale, however, the data stays stale and no new request is made. 

### Reproduction

https://codesandbox.io/s/urql-stale-while-revalidate-bug-lziis?file=/pages/index.js

### Urql version

urql v2.2.3

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/FormidableLabs/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/FormidableLabs/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by devunt** [comment] 2022-08-28 08:00
Same issue with urql 3.0.1.
In ssrExchange `staleWhileRevalidate` was to `true` but the stale flag remains true without any network requests being made.

**Comment by kitten** [comment] 2022-09-21 13:47
I'll close this in favour of #2689 since that's more precise and talks about the root cause here, which is that `ssrExchange` has a missing `requestPolicy` check

**Closed** 2022-09-21 13:48 UTC
Labels: duplicate ♊
