### ISSUE TITLE
Graphcache's cache.invalidate not working under some conditions

### ISSUE THREAD

**Issue by ostrebler** [FormidableLabs/urql#1879] opened 2021-08-21 20:30 UTC
urql version & exchanges: 2.0.4 (@urql/exchange-graphcache: 4.3.0)

**Steps to reproduce**

Let's say with have these types : 

```graphql
type Meal {
    id: ID! 
    name: String! 
    user: User! 
  }

  type Query {
    meals(user: ID!): [Meal!]!
  }

  type Mutation {
    addMeal(name: String!, user: ID!): Meal!
  }
```

Then, the following urql client definition : 

```typescript
export const client = createClient({
  url,
  requestPolicy: "cache-and-network",
  fetchOptions() {
    const currentUser = useStore.getState().currentUser;
    if (!currentUser) return {};
    return { headers: { authorization: currentUser.token } };
  },
  exchanges: [
    dedupExchange,
    cacheExchange({
      updates: {
        Mutation: {
          addMeal({ addMeal }, __, cache) {
            cache.invalidate("Query", "meals", {
              user: addMeal.user.id
            });
          }
        }
      }
    }),
    errorExchange({
      onError({ graphQLErrors, networkError }) {
        // ...
      }
    }),
    fetchExchange
  ]
});
```

**Expected behavior**

When executing `addMeal`, the `meals` query should be refetched.

**Actual behavior**

When executing `addMeal`, the `meals` query is refetched due to invalidation **only** if there is only one instance of `useQuery` for `meals` in the code. If you have two `useQuery` for that query, nothing is refetched.

It's not that the `useQuery`s are not triggering a rerender, no actual query is sent to the backend when you go from one to two `useQuery`s then execute `addMeal`.

**Comment by kitten** [comment] 2021-08-21 21:02
Can you check whether your `@urql/core` version is already upgraded to at least `v2.2.0` please? We did fix a regression that affected duplicate sources, so I'm not sure whether that's already been addressed by this patch. 🤔

See: https://github.com/FormidableLabs/urql/blob/main/packages/core/CHANGELOG.md#220

**Comment by kitten** [comment] 2021-08-21 21:27
Duplicate of #1878

**Closed by kitten** 2021-08-21 21:27 UTC
Labels: bug 🐛
