### ISSUE TITLE
RFC: svelte-urql: enable to query in SvelteKit load() function

### ISSUE THREAD

**Issue by MichaelBailly** [FormidableLabs/urql#1819] opened 2021-07-21 15:43 UTC
## Summary

SvelteKit allows ServerSide rendering of the web application pages. One of the main benefit is to be able to load backend data from the server, have it rendered as HTML. The SvelteKit way of doing it is by adding the pre-rendering code in the `<script context="module">` part of the page.

One ideal setup would be to:

- in script context="module": instanciate the urql client
- in script context="module": create the operationStore
- in script context="module": query(operarionStore)
- in script context="module": pass the operationStore to component through props
- in script: get back the component from store
 
However, Svelte Contexts are not available there. Which means the query(operationStore) cannot run, because it fetches the urql client through svelte contexts [here](https://github.com/FormidableLabs/urql/blob/main/packages/svelte-urql/src/operations.ts#L72).

Having a way to pass the urql client to the query function would allow such use case.

## Proposed Solution

Change the [query function signature](https://github.com/FormidableLabs/urql/blob/main/packages/svelte-urql/src/operations.ts#L69) from:

```javascript
query<Data = any, Variables = object>(
  store: OperationStore<Data, Variables>
): OperationStore<Data, Variables>
```

to

```javascript
query<Data = any, Variables = object>(
  store: OperationStore<Data, Variables>,
  opts?: {
    client?: Client
  }
): OperationStore<Data, Variables>
```

This would allow to either use query like now:

```javascript
const todos = operationStore(todoRequest);
query(todos);
```

or to use specify a custom client

```javascript
const client = createClient({ url: 'http://localhost:3000/graphql' });
const todos = operationStore(todoRequest);
query(todos, { client });
```

Having that in place, SvelteKit users can easily plug their code:

```svelte
<script context="module">
const client = createClient({ url: 'http://localhost:3000/graphql' });
const todos = operationStore(todoRequest);
query(todos, { client });

return {
  props: {
    client, // pass the client to the component
    todos
  },
  context: {
    client // pass the client to sub-pages 'context="module"' part, example if we are in a __layout.svelte 
  }
};
</script>

<script>
import { setClient } from '@urql/svelte';
export let client;
export let todos;

// let's say it's the root __layout.svelte, setting the client here
// allows to use query(store) directly in all components thereafter
setClient(client); 
</script>

{$todos.data.todos.length}
```

Please tell me what you think about this proposal.

**Comment by disbelief** [comment] 2021-10-16 17:04
I'm wondering what the current state of @urql/svelte + SvelteKit + SSR is?

It would be fantastic to get a canonical example of how to do it, particularly around the SvelteKit `load` function and the urql client.

I'm using a strategy based off of this gist: https://gist.github.com/sastan/85cf3d011b152a80d3a5933a09df21f6
(without the response normalization stuff).

The `__layout` creates an instance of the urql `Client` and stores it in `stuff` (SvelteKit renamed the loader `context` to `stuff` in latest version).

Then the route's `load` function uses `client.query` to create the `OperationStore` and await the results of the query. Then it provides the `operationStore` as a prop to the Svelte component. The Svelte component then calls `query(operationStore)` on the prop it receives.

This seems to work most of the time, but [variable reactivity](#1036) doesn't work. Specifically, changing the `variables` doesn't seem to trigger a new request.

I've tried both `$store.variables = nextVariables` and `store.set({ variables: nextVariables })` with and without `refetch()`. The `operationStore` does get written to but the actual client request's variables don't change and no new request is sent.

Guessing it has something to do with the way the OperationStore is created in the loader, passed to the component, and `query()` called upon it, but I've walked through the debugger and can't figure out what the problem is.

Also the above solution seems a bit kludgy and I'm guessing (hoping) there's a more straightforward way to do this?

**Comment by JoviDeCroock** [comment] 2021-10-17 10:30
I think I found a solution @disbelief it's a bit hacky but shows the general idea 😅 https://github.com/JoviDeCroock/urql-svelte-kit/commit/fe552952f8f510bd60aab7833ec4f4124d38c331

**Comment by frederikhors** [comment] 2021-10-17 11:11
Can we please contact someone from SvelteKit's team?

**Comment by disbelief** [comment] 2021-10-17 11:22
@JoviDeCroock thanks this is a promising approach! It would take me some time to refactor my app like this, so I can't confirm it works for me just yet.

**Comment by disbelief** [comment] 2021-10-17 11:24
@Rich-Harris wondering if you could provide any insight or know a good person on the SvelteKit team we could ask about this?

**Comment by nimmolo** [comment] 2021-10-29 23:18
I feel like @bluwy may know a lot about GraphQL and SvelteKit... the contributors over there seem super busy though

**Comment by bluwy** [comment] 2021-10-31 10:27
Hey :wave: I've not used urql before but I can give some thoughts on this.

> Re: SvelteKit/Vite `optimizeDeps` workaround

Those should be fixed since a couple months ago, we've fixed Vite's pre-bundling in vite-plugin-svelte side which resolved most of the quirks in the past.

> Re: graphql query and serialization flow

I've actually written a blog about [Apollo and Sapper](https://bjornlu.com/blog/using-apollo-client-in-sapper/) before, but needs to be adapted to urql and SvelteKit.

Looking back at the blog, I actually prefer Method 1 now and it seems to be closer to what most of the discussion here proposes. I'm not sure if the trick shown works in SvelteKit anymore, but if it does I'd be interested to know.

> Re: RFC

I think it makes sense to allow querying in `context="module"` too since the data could be one-off and it makes sense to do that way. Otherwise if you would expect to refetch the data whenever some state changes, querying in the component instance may be easier to handle that. Which with a mix of Method 1 above, should be possible. Take my opinion with a grain of salt though.

**Comment by AndreasHald** [comment] 2021-11-18 14:43
Just throwing in my two cents here, since I have been facing this same issue with the Apollo client and are looking towards creating some samples using Urql instead to propose the switch in our app.

Svelte kit actually caches fetch calls in the load function to make sure it does not make the call again on the client. What I did using Apollo client was simply instantiating the client using the fetch method provided in the load function, and then using the client to query the api both during ssr and csr svelte kit then automatically recognizes that the second fetch request on the client is identical to the one performed during ssr and serves the "cached" response.

**Comment by disbelief** [comment] 2021-11-18 15:10
This makes sense: no need to do our own request/response serialization when SvelteKit's `fetch` does it out of the box already.

But for some reason things get messed up (for me) when working with urql `OperationStores` that are initiated in the `load` function and interacted with in the client (eg. changing variables, refetching, etc).

Perhaps instead of creating the `OperationStore` and returning it as a prop, the load function should just execute the query during SSR so it's serialized into the client's fetch function?

```svelte
// src/routes/__layout.svelte

<script context="module">
  import { createClient } from '@urql/svelte';

  export async function load({ fetch, stuff }) {
    const client = createClient({
      // Pass in the fetch from sveltekit to have access to serialized requests
      fetch,
    });

    return {
      stuff: { ...stuff, client },
      props: { client }
    }
  }
</script>


// src/routes/myRoute.svelte

<script context="module">
  import { browser } from '$app/env'

  export async function load({ stuff }) {
    if (!browser) {
      stuff.client.query(SOME_QUERY, SOME_VARIABLES);
    }
    return {
      props: {}
    };
  }
</script>

<script>
  import { query, operationStore } from '@urql/svelte';

  const opStore = operationStore(SOME_QUERY, SOME_VARIABLES);
  // should use the serialized result in the client if the query+variables are the same
  query(opStore);

</script>
```

**Comment by AndreasHald** [comment] 2021-11-18 15:12
Alright I believe I got the same idea working.

In the layout file, you create the client, and return it as a prop, you can then set it on the context, so all child components can retrieve it, you also store it in "stuff" so your subsequent load functions has access to it, you create it using the svelte-kit provided fetch, so that it may use svelte-kit caching

```html
<!--__layout.svelte-->
<script lang="ts" context="module">
	import type { Load } from '@sveltejs/kit';
	import { createClient, setClient } from '@urql/svelte';
	export const load: Load = async ({ fetch }) => {
		const client = createClient({
			url: '/graphql',
			fetch
		});

		return {
			stuff: {
				client
			},
			props: {
				client
			}
		};
	};
</script>

<script lang="ts">
	export let client;
	setClient(client);
</script>

<slot />
```

On on routes you can now 
```html
<!-- /someroute/index.svelte -->
<script lang="ts" context="module">
	export const load: Load = async ({ stuff }) => {
		const store = operationStore(`
		    query {
		      tasks {
		        name
		      }
		    }
		  `);

		await stuff.client.query(store.query, store.variables, store.context).toPromise();

		return {
			props: {
				store,
			}
		};
	};
</script>

<script lang="ts">
	import type { Load } from '@sveltejs/kit';
	import { operationStore, query } from '@urql/svelte';

	export let store;
	query(store);
</script>
```

Your store will then have the value server side rendered but not make multiple requests :)

**Comment by disbelief** [comment] 2021-11-18 15:14
@AndreasHald this is what I was doing but it runs into problems when modifying variables or refetching on the client side.

Just realized after posting my above suggestion that it won't work because the urql `query` function doesn't use the custom `client` that we instantiate in the layout.

**Comment by disbelief** [comment] 2021-11-18 15:15
Perhaps the ideal solution is to be able to provide a client (or `fetch`) to urql's `query` or `operationStore` functions?

**Comment by AndreasHald** [comment] 2021-11-18 15:16
@disbelief Yeah it seems you need to return it as a prop and call ```setClient``` in the ```__layout``` file however, it seems to work just as expected for me when updating variables.

**Comment by disbelief** [comment] 2021-11-18 15:18
Interesting. Perhaps that's a red herring / bug coming from elsewhere in my code.

**Comment by AndreasHald** [comment] 2021-11-18 15:23
@disbelief how are you reassigning variables?

This works for me
![Screenshot 2021-11-18 at 16 20 34](https://user-images.githubusercontent.com/8914722/142443780-36ba49a4-c1ae-494d-b38a-967fc338174d.png)

However this does not work
![Screenshot 2021-11-18 at 16 20 47](https://user-images.githubusercontent.com/8914722/142443817-df3588f0-70d5-4884-924f-30c43b4eca72.png)

But I think that's a svelte thing, where the "reactivity" is not aware that variables has changed unless you actually reassign it, in the example that does not work the variable being reassigned is actually variables.index however I could be wrong.

**Comment by disbelief** [comment] 2021-11-18 15:27
Yep, aware that the entire `variables` reference needs to be replaced.

I tried these two ways:

```js
$opStore.variables = { ...variables, page: page + 1 };
```

and

```js
$opStore.set({ variables: { ...variables, page: page + 1 } });

**Comment by disbelief** [comment] 2021-11-18 15:28
My currently solution is to issue a brand new operation store+query on the client to fetch the subsequent pages, vs reusing the operation store that the load function provides. Which obvs kinda sucks.

**Comment by jdgamble555** [comment] 2021-11-21 00:22
I figured it out.  Please post this [official docs](https://formidable.com/open-source/urql/docs/advanced/server-side-rendering/) as it follows the same pattern as the other frameworks.

- 1st, don't use @urql/svelte, use @url/core for sveltekit

**urql.ts**
```typescript
export const ssr = ssrExchange({
    isClient: !isServerSide,
    initialState: !isServerSide ? window['__URQL_DATA__'] : undefined,
});
...
const client = createClient({
    url: `YOUR URL`,
    exchanges: [
        dedupExchange,
        cacheExchange,
        ssr,
        ... YOUR EXCHANGES
        fetchExchange
    ]
});

export const data = `
<script lang="ts"> 
  window.__URQL_DATA__ = JSON.parse(JSON.stringify(__SSR__)); 
</script>
`;

export default client
```

**index.svelte**
```typescript
<script context="module" lang="ts">
  import { dev, browser } from '$app/env';
  import { ssr, data, client } from '../modules/urql';

  export async function load() {
    if (browser) {
      ssr.restoreData(window['__URQL_DATA__']);
    }

    let r = await client.query(....);

    const d = browser
      ? 'null'
      : data.replace('__SSR__', JSON.stringify(ssr.extractData()));

    return { props: { r, d } };
  }
</script>
<script lang="ts">

export let d: any;
export let r: any[];
...
</script>

{@html d}

```

Hope this helps someone,

J

**Comment by gmanfredi** [comment] 2021-12-05 20:43
Hey @jdgamble555,
Thanks, that was very helpful.  I've had the SSR graphql working Sapper with Apollo, but with the help of this discussion, finally got it working in SvelteKit and URQL.  For me, getting it working is particularly important for [fluid page animations](https://dev.to/buhrmi/svelte-component-transitions-5ie) since the target element needs to be already rendered on target page to have transitions work.

Regarding your example index.svelte, I think you need the `toPromise()` on the query.  I have my module script like this:
```
<script context="module">
  import { browser } from "$app/env"
  import client, { ssr, data } from "@/graphql/urql"
  import GET_POST_DETAIL from "@/graphql/queries/getPostDetail"

  export const load = async ({ page: { params } }) => {
    const { id } = params

    if (browser) ssr.restoreData(window["__URQL_DATA__"])
    let result = await client.query(GET_POST_DETAIL, { id }).toPromise()
    const _SSRData = browser ? "null" : data.replace("__SSR__", JSON.stringify(ssr.extractData()))

    return {
      props: {
        _SSRData,
        topic: result.data?.getTopic,
        id
      }
    }
  }
</script>
```

**Comment by disbelief** [comment] 2021-12-06 09:42
While the above solution is appreciated and seems promising (thank you @jdgamble555), I'd argue that the goal of the `@urql/svelte` package should be to support SvelteKit out of the box, as it will be the most common use-case of Svelte and GraphQL going forward. So, we still need a canonical "SvelteKit way" of doing this.

**Comment by jdgamble555** [comment] 2021-12-06 14:46
@gmanfredi - Yes, you need `toPromise()`.  I was simplifying my code and missed that!  (You also should be using typescript, but that is your preference ;) )

@disbelief - @urql/svelte simply cannot work with sveltekit the way it currently stands, as it was not written to work with SSR (although it should have so it could work with Sapper).  That being said, you can use @urql/core without problems.  You can actually do this with Angular as well, although they don't claim to support it (I have written apps with urql/Angular).

Since the `fetch` command in sveltekit automatically [saves the data](https://kit.svelte.dev/docs#loading-input-fetch) (I think using cookies?), you should be able to replace the fetch in URQL somehow with the Sveltekit fetch version, as the `sveltekit` way of doing things.

I have not tested it, but it should be possible like I did [here](https://github.com/FormidableLabs/urql/issues/1403#issuecomment-784735426).  Let me know if someone simplifies this!

J

**Comment by disbelief** [comment] 2021-12-07 17:18
@jdgamble555 yes the solutions myself and others posted above do what you describe -- passing the SvelteKit-provided `fetch` function to the urql client. It seems to mostly work, but I was having some issues when creating the OperationStore in the `load` function, and then passing it as a prop to the component. Not all of the OperationStore's functionality worked as expected.

**Comment by jdgamble555** [comment] 2021-12-07 22:31
Hi @disbelief.  I was talking about using the svelte `fetch` that does all this automatically and passing it to the exchanges as `fetch`, which you can change.  The examples above are using `@urql/svelte` and `operationStore`.  I don't see how `@urql/svelte` can work at all with the ssr restrictions.

I think if you pass in the `fetch` to `@urql/core`, like I did in my [angular example](https://github.com/jdgamble555/angular-fire-dgraph/blob/master/src/app/core/urql.module.ts#L59) , it might work.

J

**Comment by Rich-Harris** [comment] 2021-12-07 22:59
Hi all — I was tagged earlier so have been dimly aware of this thread happening; sorry for not weighing in sooner. I will read the whole thing when I get a chance!

In the meantime, I just wanted to make you aware of this: https://github.com/sveltejs/kit/issues/2979. It's a proposal for (hopefully) making it easy for things like `svelte-urql` hook into `load` for SSR purposes. I _think_ it would work similarly to the Angular example above? Would love to know if you have thoughts on whether this API would meet your needs (feel free to comment on that issue), and apologies if it's a complete red herring.

**Comment by disbelief** [comment] 2021-12-09 11:03
@jdgamble555 yes it's possible to provide Svelte's `fetch` to `@urql/svelte`:
1. Pass Svelte's `fetch` to the `createClient` function in `load`
2. Return that `client` as a prop from `load`
3. Call `setClient` with that prop in the component

The above _should_ use the sveltekit-fetch-enabled client for all `@urql/svelte` functions including the creation of OperationStores, etc.

**Comment by disbelief** [comment] 2021-12-09 11:11
@Rich-Harris thanks for weighing in, I'm sure you're pretty busy so appreciate the reply. The linked [proposal](https://github.com/sveltejs/kit/issues/2979) looks like a quite useful convenience helper.

Generally what I was looking for is a well-defined convention for using an external client in SvelteKit's `load` function that works as expected under both SSR + browser, and takes advantage of the SvelteKit's serialized requests in `fetch`. 

Perhaps the current "monstrosities" approach you outlined in that issue is the canonical way of doing this at the moment?

**Comment by Rich-Harris** [comment] 2021-12-09 15:50
It is the canonical approach right now, yes (or at least it's the approach I've been taking). Given the positive feedback on the proposal so far, I'm keen to make a start on it fairly soon, so hopefully it won't be canonical for long

**Comment by rogueyoshi** [comment] 2021-12-14 05:07
> @jdgamble555 yes it's possible to provide Svelte's `fetch` to `@urql/svelte`:
> 
> 1. Pass Svelte's `fetch` to the `createClient` function in `load`
> 2. Return that `client` as a prop from `load`
> 3. Call `setClient` with that prop in the component
> 
> The above _should_ use the sveltekit-fetch-enabled client for all `@urql/svelte` functions including the creation of OperationStores, etc.

Will this solution allow proper prerendered routes using the query information?

**Comment by disbelief** [comment] 2021-12-14 09:19
@rogueyoshi in my experience, yes it works.

**Comment by jdgamble555** [comment] 2021-12-14 14:43
@disbelief - I was saying I cannot see how @urql/svelte would work in sveltekit, not whether or not passing the fetch would work.  I was simply stating that what was mentioned above, was not the same thing.

Either way, the problem is that the fetch function only exists in the load function.  That suggests you need to repass the fetch to the load function for every single component, instead of doing it one time through out your app.  That is a problem. 

Sharing a `ts` or `js` file that already loads the client function one time, would be the best practice.  I am wondering if it might be better to just create the same cookie that the fetch function does internally (not sure what it does exactly under the hood) so that you are not limited to the load function.

Anyone have any thoughts not being limited to the load function?

J

**Comment by chbert** [comment] 2022-02-04 19:33
Is there any update on this issue?

**Comment by kitten** [comment] 2022-05-24 18:48
Obsolete and potentially resolved by: https://github.com/FormidableLabs/urql/pull/2370
The API basically now just exposes store factories that are a transparent conversion from sources to a readable store.

**Closed by kitten** 2022-05-24 18:48 UTC
Labels: future 🔮
