### ISSUE TITLE
next-urql: Switch from NextPageContext to PartialNextContext breaks usage with NextPage type

### ISSUE THREAD

**Issue by impulse** [FormidableLabs/urql#1213] opened 2020-12-10 07:09 UTC
Nextjs `NextPage` uses `NextPageContext` to type the context. With the recent update in urql to `PartialNextContext`, this breaks passing in a component typed with `NextPage` into `withUrqlClient`.

urql version & exchanges:
```
"@urql/devtools": "^2.0.2",
"@urql/exchange-graphcache": "^3.3.2",
"next": "10.0.3",
"next-urql": "^2.1.1",
"urql": "^1.11.4",
```
**Steps to reproduce**

Use the official Nextjs example <https://nextjs.org/docs/api-reference/data-fetching/getInitialProps#typescript> and pass it in `withUrqlClient`.

```tsx
import { NextPage } from "next";
import { withUrqlClient } from "next-urql";
import { createUrqlClient } from "../lib/createUrqlClient";

interface Props {
  userAgent?: string;
}

const Page: NextPage<Props> = ({ userAgent }) => (
  <main>Your user agent: {userAgent}</main>
);

Page.getInitialProps = async ({ req }) => {
  const userAgent = req ? req.headers["user-agent"] : navigator.userAgent;
  return { userAgent };
};

export default withUrqlClient(createUrqlClient)(Page);
```

**Expected behavior**
No type errors

**Actual behavior**
```
Argument of type 'FunctionComponent<Props> & { getInitialProps?(context: NextPageContext): Props | Promise<Props>; }' is not assignable to parameter of type 'NextComponentType<PartialNextContext, {}, {}>'.
  Type 'FunctionComponent<Props> & { getInitialProps?(context: NextPageContext): Props | Promise<Props>; }' is not assignable to type 'FunctionComponent<WithUrqlProps> & { getInitialProps?(context: PartialNextContext): {} | Promise<{}>; }'.
    Type 'FunctionComponent<Props> & { getInitialProps?(context: NextPageContext): Props | Promise<Props>; }' is not assignable to type '{ getInitialProps?(context: PartialNextContext): {} | Promise<{}>; }'.
      Types of property 'getInitialProps' are incompatible.
        Type '((context: NextPageContext) => Props | Promise<Props>) | undefined' is not assignable to type '((context: PartialNextContext) => {} | Promise<{}>) | undefined'.
          Type '(context: NextPageContext) => Props | Promise<Props>' is not assignable to type '(context: PartialNextContext) => {} | Promise<{}>'.
            Types of parameters 'context' and 'context' are incompatible.
              Type 'PartialNextContext' is missing the following properties from type 'NextPageContext': pathname, query
```

**Comment by acedeywin** [comment] 2020-12-11 05:49
I am currently having this same issue.

**Comment by Sulman633** [comment] 2020-12-16 00:35
The same issue as well, please merge as soon as possible

**Comment by kitten** [comment] 2020-12-16 02:50
We're on track to get this merged and released this week, but we'd like to ensure that the fixed types work as intended without pulling in Next as a dependency on our end, as it's been before, hence we're spending more time on testing these types 🙇

As it stands though, it's alright, please work around this by casting the type forcefully until this is available; and maybe give the packages as provided by CodeSandbox CI a try on the PR above.
Comments & pings don't speed up our process as we're actively working on this, but testing these prebuilds out does help us a lot! 🙌

**Comment by impulse** [comment] 2020-12-16 06:51
@kitten I'd be up for testing it out, but I didn't understand your instructions. Where do I go from here?
![image](https://user-images.githubusercontent.com/8146736/102314876-73b59100-3f73-11eb-8729-2c196685c63b.png)

**Comment by JoviDeCroock** [comment] 2020-12-16 11:06
@impulse this is the provided package: `https://pkg.csb.dev/FormidableLabs/urql/commit/3ec75e59/next-urql` you can paste this as the version for `next-urql`.

Alternatively would you mind trying: `withUrqlClient(options)<NextPage>`

**Comment by impulse** [comment] 2020-12-16 11:22
@JoviDeCroock this is what I get when installing the package from above URL:
```
Argument of type 'NextComponentType<NextPageContext, Props, Props>' is not assignable to parameter of type 'NextComponentType<PartialNextContext, {}, {}>'.
  Type 'ComponentClass<Props, any> & { getInitialProps?(context: NextPageContext): Props | Promise<Props>; }' is not assignable to type 'NextComponentType<PartialNextContext, {}, {}>'.
    Type 'ComponentClass<Props, any> & { getInitialProps?(context: NextPageContext): Props | Promise<Props>; }' is not assignable to type 'ComponentClass<WithUrqlProps, any> & { getInitialProps?(context: PartialNextContext): {} | Promise<{}>; }'.
      Type 'ComponentClass<Props, any> & { getInitialProps?(context: NextPageContext): Props | Promise<Props>; }' is not assignable to type '{ getInitialProps?(context: PartialNextContext): {} | Promise<{}>; }'.
        Types of property 'getInitialProps' are incompatible.
          Type '((context: NextPageContext) => Props | Promise<Props>) | undefined' is not assignable to type '((context: PartialNextContext) => {} | Promise<{}>) | undefined'.
            Type '(context: NextPageContext) => Props | Promise<Props>' is not assignable to type '(context: PartialNextContext) => {} | Promise<{}>'.
              Types of parameters 'context' and 'context' are incompatible.
                Type 'PartialNextContext' is not assignable to type 'NextPageContext'.
                  Types of property 'pathname' are incompatible.
                    Type 'string | undefined' is not assignable to type 'string'.
                      Type 'undefined' is not assignable to type 'string'.ts(2345)
```

**Comment by danilo-nzyte** [comment] 2021-01-08 07:41
I'm receiving the same error as defined above.

Are you able to offer some guidance to a TypeScript newbie of exactly how I might do what you've mentioned in your post @kitten?
>"As it stands though, it's alright, please work around this by casting the type forcefully until this is available"

**Comment by spdev01** [comment] 2021-01-12 02:31
I am currently experiencing this as well. Is there currently any update/workaround for this issue?

**Comment by wgolledge** [comment] 2021-01-12 09:34
Hi @spdev01, I'm currently working on getting a solution out.

In the meantime, if you are struggling with the type error then as an interim solution you should be able to use a Type Assertion on the `NextPage` component. Something along the lines of:

``` js
import { withUrqlClient, NextComponentType } from 'next-urql';

...

export default withUrqlClient(options)(Page as NextComponentType);

**Closed** 2021-01-13 10:30 UTC
Labels: bug 🐛
