### ISSUE TITLE
(graphcache) Query is not updated after cache update

### ISSUE THREAD

**Issue by augustas1** [FormidableLabs/urql#2768] opened 2022-10-27 08:35 UTC
### Describe the bug

Since graphcache v5.0.2 seems that queries with `requestPolicy: "network-only"` are no longer updated as before.

## Example
Query:
```
notes {
  id
  status # e.g. TODO
}
```

Mutation:
```
completeNote(id: 1, status: COMPLETED) {
  id
  status
}
```

After mutation, I see that cache is updated with `status: COMPLETED`, but query is not updated (to trigger React component rerender).

In graphcache v5.0.1 queries are updated even with `requestPolicy: "network-only"`.

### Reproduction

-

### Urql version

@urql/exchange-graphcache v5.0.2 (5.0.1 works fine)
urql v.3.0.3

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/FormidableLabs/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/FormidableLabs/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment] 2022-10-27 10:49
Hey, would you mind trying 5.0.3? As there is no reproduction present it's quite hard for me to tell whether this is related to the fix that went out in that version...

**Comment by augustas1** [comment] 2022-10-27 11:12
Hey,
Yes sorry, I tried 5.0.3 as well - issue still there.
(I wrote 5.0.2 just to highlight it was introduced there)

**Comment by frederikhors** [comment] 2022-10-27 11:13
> Hey, Yes sorry, I tried 5.0.3 as well - issue still there. (I wrote 5.0.2 just to highlight it was introduced there)

Please create a reproduction.

**Comment by enex** [comment] 2022-10-28 19:26
I experienced the same issue however in my case I only chose this policy to work around a previous bug which seems to be fixed now.

**Comment by focux** [comment] 2022-11-02 21:53
I'm having this same issue as well, it works for me on version `5.0.1` but does not work on any version after that, tested on the latest version (5.0.4). This is in React Native by the way.

For now, the workaround is to pin the graphcache version to `5.0.1`.

**Comment by Nickersoft** [comment] 2022-11-04 17:52
I think I may have just run into this as well. I have Renovate Bot enabled so it auto-upgraded without me realizing. I noticed that my `writeFragment()` and `invalidate()` calls were working super inconsistently – sometimes it would update the cache/UI, othertimes it wouldn't. Downgrading to 5.0.1 does seem to fix the issue as far as I can tell!

**Comment by JoviDeCroock** [comment] 2022-11-04 17:55
Look, all we are asking for is a reproduction 😅 it's really hard for us as maintainers to see a bunch of "me too" messages, so if any of y'all could help us reproduce this then we can help you!

**Comment by Nickersoft** [comment] 2022-11-04 17:57
I know haha 😅  I think it's a bit hard for me just because it deals with post-mutation cache updating, and the public Star Wars API I usually create my repros around doesn't handle mutations. I'll poke around with it today to see if maybe I can reproduce it with a local resolver or something!

**Comment by augustas1** [comment] 2022-11-04 17:59
Sorry, was quite busy.
Is there any templates e.g. in codesandbox to create a reproduction fast?

**Comment by JoviDeCroock** [comment] 2022-11-04 18:00
Yes, the issue template actually offers one when you are creating an issue. The template can be found here with the links https://github.com/FormidableLabs/urql/blob/main/.github/ISSUE_TEMPLATE/bug_report.yaml

**Comment by Nickersoft** [comment] 2022-11-04 18:58
Gah I just attempted with the `web-collections` example and wasn't able to repro off the bat. Like I said, at least for me, there doesn't seem to be a solid rhyme or reason as to when the cache updates fail. Not sure what the experience of others has been, though.

**Comment by augustas1** [comment] 2022-11-04 21:39
Damn, @Nickersoft you're right - I spent decent amount of time trying reproduce this on codesandbox, but failed :/.

In the app I'm working on, the data models are more complex of course, but couldn't find a reason why it fails there, but not on codesandbox.

**Comment by Nickersoft** [comment] 2022-11-05 05:38
@JoviDeCroock Do you have any advice on how to better debug the cache? The URQL dev tools are helpful, but only when everything works well – when the cache doesn't update, all the dev tools tell me is that it isn't updating lol. I'm using an offline cache, but it looks like all the data is stored in a single row in the database? I'm not even sure I know how to copy the value out of the database to inspect it. This isn't the first time I've run into either cache regressions or breakages URQL, and it'd be helpful to have some kind of playbook to help debug besides trying to just step through source-mapped code. Curious how you guys approach these fixes when you work on them. 

I'll try digging a bit deeper to see if I can find any red flags that could have caused something like this to break in that recent version release. No promises, though haha 😅

**Comment by augustas1** [comment] 2022-11-05 07:01
With urql devtools I only managed to figure out that cache doesn't update in this scenario.

I also tried a different approach by using a local module (and reverting commits).
I managed to pin point commit to where the issue was introduced:
https://github.com/FormidableLabs/urql/commit/707b688c6a0d4616d35bc7190f40c204be8a7637

**Comment by JoviDeCroock** [comment] 2022-11-05 07:05
If you wanna test whether that is the issue try adding __typename to your mutation and see if it still fails, that should be the only change that commit _can_ introduce. (On phone atm)

**Comment by augustas1** [comment] 2022-11-05 07:21
Adding `__typename` didn't help.

In that commit (https://github.com/FormidableLabs/urql/commit/707b688c6a0d4616d35bc7190f40c204be8a7637) reverting line `152` seems to help.

**Closed** 2022-11-07 15:51 UTC
Labels: bug 🐛
