### ISSUE TITLE
Alternative to apolloClient.query()?

### ISSUE THREAD

**Issue by corysimmons** [FormidableLabs/urql#290] opened 2019-06-11 03:46 UTC
Sometimes I like Apollo's escape hatch of `apolloClient.query()`, does Urql have anything like this, or does it try to enforce using hooks in all instances instead?

> Sidenote: Is there a Spectrum or something for little questions like this?

**Comment by parkerziegler** [comment] 2019-06-12 06:40
👋 @corysimmons could you be looking for [`client.executeQuery`](https://github.com/FormidableLabs/urql/blob/master/docs/api.md#executequery-executesubscription-and-executemutation)? This basically allows you to execute a one-off query with just a `client` set up. You could even do this outside of React entirely if you want.

`executeQuery` returns a `source`, not a `Promise`, which is an observable-like structure from our backing stream library [`wonka`](https://github.com/kitten/wonka). For this reason, the API is a little unfamiliar to folks right now. If you like, I can spin up a simple example to show you how to do this?

I'll reach out to our OSS lead to see about getting a Spectrum set up for `urql`. I definitely think that's the direction we want to go in, a lot of us have just been working really hard on the `v1` release and the docs site.

**Comment by kitten** [comment] 2019-06-13 14:39
I'll close this as a potential duplicate of https://github.com/FormidableLabs/urql/issues/216

We also have a readme on using such an escape hatch: https://github.com/FormidableLabs/urql/blob/master/docs/extending-and-experimenting.md

Let me know if you're looking for something else, and if so I'll reopen the issue 👍

**Closed by kitten** 2019-06-13 14:39 UTC

**Comment by corysimmons** [comment] 2019-06-13 16:31
Thank you both!

No need to re-open, but I have a couple other questions:

1. Is there an `executeMutation` as well?
2. Will subscriptions work in `executeQuery`, or is there an `executeSubscription`?

**Comment by kitten** [comment] 2019-06-14 06:57
@corysimmons yes, there are three separate ones for queries, subscriptions, and mutations: https://github.com/FormidableLabs/urql/blob/master/docs/api.md#executequery-executesubscription-and-executemutation
