### ISSUE TITLE
(preact && svelte): after PR #985 no calls to server are made if navigating

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#989] opened 2020-09-18 22:31 UTC
I'm sad to open this.

After https://github.com/FormidableLabs/urql/pull/985 I cannot use my app normally.

The only change is in `package.json` from `"@urql/exchange-graphcache": "3.1.0"` to `"@urql/exchange-graphcache": "3.1.1"`.

It seems urql doesn't recognize IndexedDB anymore when first I start the app. **The DB remains empty.**

I need to reload the page after the login to make it start to write data into IndexedDB again.

What can it be?

:(

**Comment by frederikhors** [comment] 2020-09-18 22:40
Oh wow!

You already felt it here! https://github.com/FormidableLabs/urql/pull/985#issuecomment-694950735, @kitten!

I think that if you devote a few hours of work figuring out why Urql it doesn't work 100% with Svelte this project would explode among Svelte users (increasingly growing) maybe after a couple of click-catching articles on dev.to.

**Comment by kitten** [comment] 2020-09-19 01:09
I mean, we'll probably find someone internally who'd be willing to look into stabilising the Svelte bindings. That being said Svelte doesn't make it easy, especially if we're looking to preserve state across observable changes.

I did look into that issue where I saw no data and infinite loading. It happens when the initial render doesn't have any data, as if Svelte refuses to update the local state when a new value comes in.
I checked the IndexedDB data and it's consistently written for me, so I don't ever see an empty database for the current sandbox.

More interestingly, as I suspected a while ago, when I remove the SPA router and always render the List, everything works as expected and I never see an infinite loading state.

**Comment by frederikhors** [comment] 2020-09-19 22:35
@kitten!!!!!!!!!!!

I do not know if I'm happy or otherwise!

:smile:

After hours of "getting my hands dirty" with Preact I finally have proof that it is not about Svelte but about that damn change in PR https://github.com/FormidableLabs/urql/pull/985!

This is the Preact project: https://codesandbox.io/s/urql-crud-router-doesnt-update-5x5tr.

This is the problem: https://spectrum.chat/urql/help/preact-urql-preact-router-changing-route-doesnt-update-component~30779548-ed6f-4885-a011-12aba1637b9c and the steps to prove what I mean.

If after the reproduction you change the `@urql/exchange-graphcache` from `3.1.1` to `3.1.0` it works!

**THE SAME AS WITH SVELTE!**

**I'm happy BUT I'M NOT!**

_I have so many ideas to make come true and instead I spend hours solving problems that I don't know how to solve!_

:smile: :smile: :smile:

_(Do not forget to start the server simply by browsing here: https://codesandbox.io/s/apollo-server-urql-svelte-crud-h1pcl)_

**Comment by davi-mbatista** [comment] 2020-09-22 18:06
Not sure exactly how to contribute here but I'm facing a similar issue upgrading `3.1.0` to `3.1.1`. 

One mutation that I have, (that happens between navigations), wont resolve. But it will work if I omit the `storage` entry on the `offlineExchange` exchange. If I revert back to `3.1.0` this issue doesn't happen. 🤷‍♂️

**Comment by frederikhors** [comment] 2020-09-22 18:09
@davi-mbatista please downgrade to 3.1.0 and wait a little. A few days and everything will be fine! :smile:

**Comment by kitten** [comment] 2020-09-29 16:25
This PR indicates that the issue is fixed; this may also require the bindings to update though. The Preact bindings for instance have been completely updated from the `react-urql` implementation https://github.com/FormidableLabs/urql/pull/1011

Nevertheless, I'll close this issue for now, since the sandbox in the comment in this PR, derived from the above sandbox doesn't show unexpected behaviour anymore

**Closed by kitten** 2020-09-29 16:25 UTC
Labels: needs more info :raised_hand_with_fingers_splayed:
