### ISSUE TITLE
`Cannot read property 'redirect' of undefined` for fetchOptions

### ISSUE THREAD

**Issue by scyclow** [FormidableLabs/urql#162] opened 2019-01-05 17:25 UTC
I'm executing the following code to add an Authorization header to my requests. 
```
const client = new Client({
  url: 'http://localhost:5000/graphql',
  fetchOptions: () => {
    const jwtToken = jwt.get()
    if (jwtToken) {
      return {
        headers: {
          Authorization: `Bearer ${jwtToken}`
        }
      }
    }
  }
})
```

However, I'm getting the following error: `Uncaught (in promise) TypeError: Cannot read property 'redirect' of undefined`, which appears to be failing on this line: https://github.com/FormidableLabs/urql/blob/3b9c2ede23cec47a9accb363e5cc7bf4891045c4/src/modules/http-exchange.ts#L55

I'm able to fix it by returning `{}` if `jwtToken` is undefined, like so:
```
const client = new Client({
  url: 'http://localhost:5000/graphql',
  fetchOptions: () => {
    const jwtToken = jwt.get()
    if (jwtToken) {
      return {
        headers: {
          Authorization: `Bearer ${jwtToken}`
        }
      }
    } else {
      return {}
    }
  }
})
```
But, I wouldn't expect to have to do that, given https://github.com/FormidableLabs/urql/blob/master/src/modules/client.ts#L31

Feel free to close if this is the expected behavior, but it seems a bit counterintuitive to me.

**Comment by andyrichardson** [comment] 2019-01-06 21:36
Thanks for reporting - it doesn't look like this is expected behavior. I think this is due to a type discrepancy which has since been addressed in V1.

There's a [code snippet](https://github.com/FormidableLabs/urql/blob/v1/src/lib/client.ts#L35) on the V1 release which looks to solve this problem.

```tsx
const fetchOptions =
  typeof opts.fetchOptions === 'function'
    ? opts.fetchOptions()
    : opts.fetchOptions !== undefined
    ? opts.fetchOptions
    : {};
```

With regard to typing, we need to find a way to assert that known _context_ values are type safe while allowing for _any_ values. I'll update the types on V1 to address this:

```tsx
// Before
export interface Operation extends Query {
// ..
  context: Record<string, any>;
// ..
}


// After
export interface Operation extends Query {
// ...
  context: {
    [key: string]: any;
    fetchOptions: RequestInit | (() => RequestInit)
  }
// ..
}
```

**Comment by kitten** [comment] 2019-02-15 22:24
v1 is released now which means this issue was resolved / is out-of-date 👌

Some docs and a proper announcement for v1 are still in progress in pending. It's completely usable so far but the API has changed, so I have to ask for some more patience, but everything will be ready quite soon ✌️

**Closed by kitten** 2019-02-15 22:24 UTC
