### ISSUE TITLE
RFC: useQuery pause should have the option to zero-out result

### ISSUE THREAD

**Issue by CreativeTechGuy** [FormidableLabs/urql#2507] opened 2022-06-17 22:28 UTC
## Summary

_This is possibly a bug, but I'm filing a feature request because the docs make it seem like this is intentional._

As described in the docs on pausing [here](https://formidable.com/open-source/urql/docs/basics/react-preact/#pausing-usequery), a paused query holds on to the last data that it had. This isn't very useful in many cases such as the one shown in the docs. We want to pause the query because we don't have defined arguments, this is a null state which is weird when the hook still is holding on to the old data.

Steps to encounter this situation:

```
const [id, setId] = useState<null | string>(null);
const [result] = useQuery({
    query: SomeQuery,
    variables: { id },
    pause: id === null
})
```
* In the code above, we are pausing the query because `id` is currently null. The `result` at this time is undefined which is expected.
* Later we run `setId("someId")` which will then trigger the query since it is no longer paused, we will then receive data as expected.
* Sometime later we clear the id `setId(null)`. I'd expect we'd be back in the first state since but we still have the data from when `id === "someId"`.

## Proposed Solution

* If this is a bug or unintended behavior, then when `pause = true` the response should be reset to the initial state.
* If this is intended behavior, then a new option `clearOnPause = true` should be added to indicate that a paused query shouldn't hold on to the old data.

**Comment by JoviDeCroock** [comment] 2022-06-17 22:33
This is intended behavior because more often than not you could be showing a temp state or rely on a lazy query. There is already currently a way to see whether you deal with a previous result by doing (in your case) `result.operation.variables.id !== variables.id` which tells you that you are dealing with the result of a previous invocation.

**Comment by CreativeTechGuy** [comment] 2022-06-17 22:50
For reference, my use-case is a sidebar which shows more details of the selected item. It doesn't make sense to show data for an item which is no longer selected. So I'm guessing this won't be implemented in the library, correct?

**Comment by JoviDeCroock** [comment] 2022-06-17 22:53
I'm not sure how other maintainers think about this but my opinion is that we currently offer the hardest functionality, maintaining the old data while offering the bailout by the means described in my previous response. I'm personally not too big on expanding the API-surface with these.

**Comment by CreativeTechGuy** [comment] 2022-06-17 22:56
Would it make sense for the query result to indicate that it is stale when it is paused?

I'm just curious, do you find that you often need to pause queries and maintain the old data? It seems strange for that to be the default because I cannot think of a time when I've ever needed that.

**Comment by JoviDeCroock** [comment] 2022-06-17 23:01
Personally seeing this quite often as conceptually when we think about a `useQuery` invocation maintaining stability but changing inputs means that we transition from one state to the other so while the next state is pending we have a choice, we load (suspend/...) or we show the old state, the latter one has been frequent on projects I have been a part of (esp for lists, ...). In the case of pausing this could be because we are for instance dealing with a very expensive fetch, i.e. the user is typing and when the user stops typing for x amount of time we unpause and fetch, this however means that in this uncanny valley there is no result, or is there, because we can still show the previous one 😅 that's more or less the cases where I have found this behavior very fortunate because it's much harder to get this behavior, as I said before it's very easy to check whether you are dealing with an old result but the other way around is a lot more complex if the library does not support it

**Comment by CreativeTechGuy** [comment] 2022-06-17 23:02
Got it. Thanks for explaining!

**Comment by JoviDeCroock** [comment] 2022-07-22 15:11
I am going to close this out but generally I would say that this is very specific to a few cases, and can be handled as part of the view layer i.e. `if paused return null`

**Closed by JoviDeCroock** 2022-07-22 15:11 UTC
Labels: future 🔮

**Comment by m3hari** [comment] 2023-07-20 04:54
I was also expecting it to reset the old state when `paused`. what about `resetOnPause: boolean` option to make it flexible
