### ISSUE TITLE
Changing endpoint URL

### ISSUE THREAD

**Issue by tkalinowskiIress** [FormidableLabs/urql#340] opened 2019-07-11 04:33 UTC
Since version 1.1.0 when I use createClient like this:

`  
const graphqlClient = createClient({
    url: 'http://localhost:8082/graphql',
  });`

The request is being sent to `https://localhost:9998/graphql` which is my origin instead of the one I have set. Everything works fine in 1.0.5

**Comment by parkerziegler** [comment] 2019-07-21 16:33
Thanks for the report @tkalinowskiIress. Just to make sure we can help you out as quickly as possible, would you be able to spin up a sample reproduction, either on CodeSandbox or as a standalone repo?

Interestingly, I did run into this as well when developing the examples for [`reason-urql`](https://github.com/FormidableLabs/reason-urql). In that repo, it had to do with two versions of `urql` being in my `node_modules` (one for the example project, one from symlinking the `src` directory). To fix that, I used `webpack`'s `resolve` `modules`: https://github.com/FormidableLabs/reason-urql/blob/master/examples/3-mutation/webpack.config.js#L12 to always ensure we resolved `urql` from the same location (local `node_modules` of example rather than `node_modules` of `src`). It may be worth checking your dependency tree / lockfile and trying out the `resolve`.

My working theory is that, if another version of `urql` is present and it hits this line: https://github.com/FormidableLabs/urql/blob/1d278ca343ee35bb9ba738ccefba87ff6c44afea/src/context.ts#L6, then it'll just pull the `url` parameter from your domain.

**Comment by kitten** [comment] 2019-07-21 16:35
@parkerziegler yea, that sounds like a plausible explanation. If we hit two versions of urql then we'd have two different contexts that would've been created in the two different modules. Hence the client is never picked up by the other module

**Comment by tkalinowskiIress** [comment] 2019-07-22 00:10
Hi, yes you are right we figured out we had two versions present in our monorepo in different packages. One of packages used 1.0.5, second used 1.1.0. It seem there is some incompatibility between them.

**Comment by parkerziegler** [comment] 2019-07-22 00:52
🆒Yeah I think you have two solutions here:

1) If you're using `webpack`, use the `resolve` field with `modules` to first resolve the path where the version of `urql` you want to use lives. Check out the docs on [`resolve.modules`](https://webpack.js.org/configuration/resolve/#resolvemodules) to see how this works.
2) If you're using `yarn`, use `yarn`'s resolutions feature to specify _one_ version of `urql` to resolve when installing `node_modules`. Check out the docs on [`yarn resolutions`](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/).
3) Determine if you can migrate to using a single version across your monorepo. Check the [CHANGELOG](https://github.com/FormidableLabs/urql/blob/master/CHANGELOG.md) to see what changed between v1.0.5 and the version you're using (v1.1.0, right). For the most part, the only differences are small bug and type fixes, and SSR support (which shouldn't affect things if you're only using `urql` clientside).

Closing this issue for now, but I'll add a section to the docs about running into this scenario since it seems to have tripped up both you and me at some point 😅

**Closed by parkerziegler** 2019-07-22 00:52 UTC
Labels: needs more info :raised_hand_with_fingers_splayed:, question 🙋

**Comment by tkalinowskiIress** [comment] 2019-07-22 04:49
@parkerziegler Maybe you could add some warning when two versions are used at the same time, similarly to `styled-components`

**Comment by Necmttn** [comment] 2020-03-29 04:30
this issue still exists. still not figure out what causes it.

**Comment by kitten** [comment] 2020-03-29 13:01
@Necmttn check your context. This issue occurs if you either don’t provide a client or if the provider isn’t effective for the hooks. Be that because the library is duplicated or for another reason 🙂
