### ISSUE TITLE
Entity not refetching when query returns an empty array.

### ISSUE THREAD

**Issue by JoviDeCroock** [FormidableLabs/urql#378] opened 2019-08-07 13:04 UTC
**Describe the bug**
When your list is empty and your Mutation "invalidates it" it doesn't get refetched

**Steps to reproduce**
1. Make sure your `uploads` in the server are empty a cmd + s suffices
2. Upload a file

**Expected behavior**
The uploads should be refetched.

**Actual behavior**
The refetch isn't happening.

**Explanation**
This happens because initially the response is an empty array, meaning there is no `__typename` for the entities contained inside of this query.
In this case `data: { "uploads": [], "__typename": "query" }`

Following up this Mutation will invalidate the `FileUpload` type, since this is not present there won't be any reexecution of a query.

Solving this issue would effectively require access to the introspected schema since there we could inspect the data requirements of said query and see that it returns a `FileUpload`, that way we would have sufficient information when the `Mutation` is executed.

Reproductions:
- client: https://codesandbox.io/s/urql-bug-reproduction-lyb2y
- server: https://codesandbox.io/s/urql-upload-server-p49r8

**Comment by JoviDeCroock** [comment] 2019-08-13 09:16
I've been thinking about this more and I see two options options apart from schema-awareness I see for now is to hold a Set of keys named `emptyResponses`, these would be reexecuted on every `Mutation`. In an ideal world these operations would be very limited.

Second options I see is moving our default requestPolicy to `cache-and-network`, this however would imply that if we don't unmount --> mount it won't be refetched.

**Comment by tyler-johnson** [comment] 2019-08-13 15:16
As you get at, the main issue is that the cache only knows to invalidate any `__typename` found in the mutation response. This was a problem for us, as some of our mutations simply return a boolean.

So what we did to address this was implemented a copy of the cache exchange that looks for an option on the mutation context with an array of type names to invalidate. So a mutation call looks like this:

```ts
const mutate = useMutation(mutationOp);

// later
mutate(vars, {
  invalidateCacheTypenames: ["type","names","to","invalidate"]
});
```

Ideally, though, the cache exchange would expose an API for other exchanges to modify it. The way I see it, how the cache knows which query to invalidate based on a mutation is going to be implementation specific.

**Comment by kitten** [comment] 2019-08-21 11:53
I'll close this as expected behaviour for now. The normalized cache is more powerful in this regard, so I think we can safely say that this is a known limitation of the default cache :smile:

**Closed by kitten** 2019-08-21 11:53 UTC
Labels: bug 🐛

**Comment by JoviDeCroock** [comment] 2020-03-13 11:00
Hey everyone who might encounter this issue, we’ve released a fix and it’s documented right here https://formidable.com/open-source/urql/docs/basics/document-caching/#document-cache-gotchas

**Comment by acro5piano** [comment] 2021-02-24 17:03
The document moved here:

https://formidable.com/open-source/urql/docs/concepts/document-caching/#adding-typenames
