### ISSUE TITLE
@urql/svelte - Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by bmccorm2** [FormidableLabs/urql#2220] opened 2022-01-26 19:29 UTC
I'm trying to make a vanilla query call to my (functioning) graphql server using Svelte.  I've been following along [https://formidable.com/open-source/urql/docs/basics/svelte/#providing-the-client](url) but when i import anything from @urql/svelte (createClient, setClient, initClient, etc) i get the above error in my app.

This is the line the error points to in the JS bundle:
`  process.env.NODE_ENV === 'production'`

PACKAGE.JSON
`{
  "name": "svelte-app",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "rollup -c",
    "dev": "rollup -c -w",
    "start": "sirv public --no-clear"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^17.0.0",
    "@rollup/plugin-node-resolve": "^11.0.0",
    "rollup": "^2.3.4",
    "rollup-plugin-css-only": "^3.1.0",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^7.0.0",
    "rollup-plugin-terser": "^7.0.0",
    "svelte": "^3.46.2"
  },
  "dependencies": {
    "@fortawesome/free-solid-svg-icons": "^5.15.4",
    "@urql/svelte": "^1.3.3",
    "bootstrap": "^5.1.3",
    "bootswatch": "^5.1.3",
    "graphql": "^16.3.0",
    "sirv-cli": "^2.0.0",
    "svelte-fa": "^2.4.0",
    "svelte-spa-router": "^3.2.0"
  }
}`

**Comment by kitten** [comment] 2022-01-26 20:02
Currently, in ESM-based loaders and bundlers that don't define a lot of default behaviour, you'll need to manually ensure that a plugin replaces `process.env.NODE_ENV` with the appropriate value, i.e. `"development"` or `"production"`

You can find a previous duplicate of the issue here: https://github.com/FormidableLabs/urql/issues/712
Please don't forget to search for prior issue or to use a discussion if you're experiencing an issue that's breaking and unlikely to be a bug, i.e. that feels like a usage issue ♥️

I'll close this for now, since it's a duplicate, but happy to take more questions here if you need any help! 👍

**Closed** 2022-01-26 20:03 UTC

**Comment by bmccorm2** [comment] 2022-01-26 21:18
Thanks I see that one now. That fix worked fine and i am getting data back now.  Could i request that information be moved to the website?  I would imagine everyone using svelte will encounter the same error?  (maybe they are just better are searching before posting than me :)

**Comment by kitten** [comment] 2022-01-26 21:29
For sure 👍 Problem is that this is quite a common practice in libraries still, and will be until export maps are adopted more commonly to support prod/dev bundles. I believe, when Vite is used, for instance, `process.env.NODE_ENV` is supported by default

Either way, we'll look into both options, updating the docs and moving away from it in the future as soon as possible
