### ISSUE TITLE
[next-urql] "ReactDOMServer does not yet support Suspense" with getServerSideProps

### ISSUE THREAD

**Issue by OscarBarrett** [FormidableLabs/urql#916] opened 2020-07-20 06:39 UTC
When using `getServerSideProps` for a page we get a Suspense error. It only seems to happen if you use a custom App component.

The error does not occur if we use `getInitialProps` for the page instead.

urql version & exchanges:
- urql 1.9.8
- next-urql 1.0.2

**Steps to reproduce**
Minimal reproduction here. https://codesandbox.io/s/next-urql-serversideprops-bug-2cwcd?file=/pages/_app.js

e.g. https://2cwcd.sse.codesandbox.io/10 (best done in the codesandbox browser in case an instance isn't running)

**Comment by kitten** [comment] 2020-07-27 12:29
Hiya, I believe this is a duplicate of this issue now that there's been a reply over there. So I'll refer to that issue and will close this one for now :) https://github.com/FormidableLabs/urql/issues/920#issuecomment-662338663

**Closed by kitten** 2020-07-27 12:29 UTC
Labels: bug 🐛
