### ISSUE TITLE
It would be really useful if fetchOptions could allow to return a promise

### ISSUE THREAD

**Issue by richtera** [FormidableLabs/urql#326] opened 2019-06-29 16:16 UTC
I created a simple version of this by copying the fetch.ts file and allowing fetchOptions to return a promise. The benefit is that if you have to wait for an access_token or anything you don't need to add logic to each of your urql queries. Is this something that's worth a pull request? I tried to make it an exchange, but there is no standard delay pipe operation in wonka so I gave up.

**Comment by kitten** [comment] 2019-06-29 16:17
Duplicate of https://github.com/FormidableLabs/urql/issues/234

This can also be done by writing a small exchange for modifying it on the fly.

**Closed by kitten** 2019-06-29 16:17 UTC

**Comment by richtera** [comment] 2019-06-29 16:20
Any guidance how to write such exchange? I played around with this for about an hour or two.
