### ISSUE TITLE
`ssr.extractData()` return bad object in @urql/core

### ISSUE THREAD

**Issue by souricevincent** [FormidableLabs/urql#1158] opened 2020-11-16 14:51 UTC
It is not possible to use the sur as indicated in the [https://formidable.com/open-source/urql/docs/advanced/server-side-rendering/](server-side-rendering) documentation because ssr.extractData() returns an object with like this : 
```
{
  '2121602754': {
    data: '{"getCityByName":{"id":"2711537","name":"Gothenburg","country":"SE","coord":{"lon":11.97,"lat":57.71,"__typename":"Coordinates"},"__typename":"City"}}',
    error: undefined
  }
}
```
'2121602754', I don't know what it is?

If I follow the documentation, I should receive this instead :
```
{
    data: '{"getCityByName":{"id":"2711537","name":"Gothenburg","country":"SE","coord":{"lon":11.97,"lat":57.71,"__typename":"Coordinates"},"__typename":"City"}}',
    error: undefined
  }
```

I logged client response and I see that :
```
{
  operation: {
    key: 2121602754,
    query: {
      kind: 'Document',
      definitions: [Array],
      loc: undefined,
      __key: 3654050794
    },
    variables: {},
    kind: 'query',
    context: {
      url: 'https://graphql-weather-api.herokuapp.com/',
      fetchOptions: undefined,
      fetch: [Function],
      preferGetMethod: false,
      suspense: false,
      requestPolicy: 'cache-first',
      meta: [Object]
    },
    operationName: [Getter]
  },
  data: {
    getCityByName: {
      id: '2711537',
      name: 'Gothenburg',
      country: 'SE',
      coord: [Object],
      __typename: 'City'
    }
  },
  error: undefined,
  extensions: undefined
}
```

So, `2121602754` is a `operation.key`... But I don't want a key in `ssr.extractData()` or, have you a method for deduct a key ?

urql version & exchanges: 
@urql/core: 1.15.1

**Steps to reproduce**
follow the documentation

Thk's

**Comment by kitten** [comment] 2020-11-16 15:21
Hiya, what do you mean by "use the sur"?

Also this is intended behaviour and not a bug. You can have multiple queries, so the cached results by the `ssrExchange` and its extracted data hence is keyed by how we identify queries: by operation keys. Otherwise how would we differentiate between multiple results. That's basically why the hydration data is split between each use of a query that's been seen during SSR.

So, I assume there's a specific use-case you have here that isn't outlined in the documentation, if so please feel free to ask about it and I'll close this in the meantime, as it's not an issue that needs a resolution for now, but generally taking this at face value, this all looks as it should. :+1:

**Closed by kitten** 2020-11-16 15:21 UTC

**Comment by souricevincent** [comment] 2020-11-17 19:47
Hi, it's "use the ssr" sorry. I'm bad, it's ok for me. Thk's
