### ISSUE TITLE
cache-and-network not hitting network if found in cache. Behaving as if it were cache-first

### ISSUE THREAD

**Issue by JohnAtFenestra** [FormidableLabs/urql#1037] opened 2020-10-05 15:34 UTC
When a hit is available in the cache, the cached version is retrieved but the network is never checked.

urql version & exchanges:

├─ @urql/core@1.13.1
├─ @urql/devtools@2.0.2
├─ @urql/exchange-graphcache@3.1.3
└─ @urql/introspection@0.1.0

**Steps to reproduce**

Scenario:

Schema:

```graphql
enum ActionKind {
  LAST
  ALL
  HANDLED_ERROR
  UNHANDLED_ERROR
}

type PingListResult {
  list: [String]
}

type PingStringResult {
  value: String
}

type PongIntResult {
  count: Int
}

union QueryResult = PingStringResult | PingListResult | ErrorResult
union MutationResult = PongIntResult | ErrorResult

type ErrorResult {
  message: String
}

type Mutation {
  pong(message: String!): MutationResult
}

type Query {
  ping(action: ActionKind): QueryResult
}

type PongAction {
  message: String
}

type Subscription {
  ponged: PongAction
}
```

Starting query:

```javascript
const query = `
query SuperPing($action: ActionKind) {
  Ping1: ping(action: $action) {
    ...on PingStringResult {
      value
    }
    ...on PingListResult {
      list
    }
    ...on ErrorResult {
      message
    }
  }
  Ping2: ping(action: LAST) {
    ...on PingStringResult {
      value
    }
    ...on PingListResult {
      list
    }
    ...on ErrorResult {
      message
    }
  }
}
`
```

Offline support:

```javascript
export const offlineSupport = {
  updates: {
    Mutation: {
      pong(result, args, cache, info) {
        const currentCachedList = cache.resolve(
          "PingListResult:listResult",
          "list"
        )
        const frozenAry = JSON.parse(JSON.stringify(currentCachedList))
        console.log({ frozenAry })
        console.log({ result })
        console.log({ args })
        cache.updateQuery({ query, variables: { action: "ALL" } }, data => {
          console.log(data)
          data.Ping1.list.push(args.message)
          return data
        })
        console.log({ cache })
        console.log({ info })
      }
    }
  },
  optimistic: {
    pong(variables, cache, info) {
      console.log(variables)
      const currentList = cache.resolve("PingListResult:listResult", "list")
      return {
        __typename: "PongIntResult",
        count: currentList.count + 1
      }
    }
  },
  keys: {
    PingStringResult: () => null,
    PingListResult: data => {
      console.log(data)
      return "listResult"
    }
  }
}
```

Mutation

```javascript
export async function runNormalMutation(message) {
  const mutation = `
mutation pong($message: String!) {
  pong(message: $message) {
    ...on PongIntResult {
      count
    }
    ...on ErrorResult {
      message
    }
  }
}
`
  return await adapter.mutate(
    mutation,
    { message },
    { additionalTypenames: ["PingStringResult", "PingListResult"] }
  )
}
```
After running the mutation (which seems to have a second bug in that the value is added twice, but not important at the moment), running the query always returns the cached results. The expectation would be that the system would hit the cache first but then check the server (unless offline).

<details>
<summary>placeholder</summary>

```javascript
{
  "queries": {
    "operation": {
      "key": 971172347,
      "query": {
        "kind": "Document",
        "definitions": [
          {
            "kind": "OperationDefinition",
            "operation": "query",
            "name": {
              "kind": "Name",
              "value": "SuperPing"
            },
            "variableDefinitions": [
              {
                "kind": "VariableDefinition",
                "variable": {
                  "kind": "Variable",
                  "name": {
                    "kind": "Name",
                    "value": "action"
                  }
                },
                "type": {
                  "kind": "NamedType",
                  "name": {
                    "kind": "Name",
                    "value": "ActionKind"
                  }
                },
                "directives": []
              }
            ],
            "directives": [],
            "selectionSet": {
              "kind": "SelectionSet",
              "selections": [
                {
                  "kind": "Field",
                  "alias": {
                    "kind": "Name",
                    "value": "Ping1"
                  },
                  "name": {
                    "kind": "Name",
                    "value": "ping"
                  },
                  "arguments": [
                    {
                      "kind": "Argument",
                      "name": {
                        "kind": "Name",
                        "value": "action"
                      },
                      "value": {
                        "kind": "Variable",
                        "name": {
                          "kind": "Name",
                          "value": "action"
                        }
                      }
                    }
                  ],
                  "directives": [],
                  "selectionSet": {
                    "kind": "SelectionSet",
                    "selections": [
                      {
                        "kind": "InlineFragment",
                        "typeCondition": {
                          "kind": "NamedType",
                          "name": {
                            "kind": "Name",
                            "value": "PingStringResult"
                          }
                        },
                        "directives": [],
                        "selectionSet": {
                          "kind": "SelectionSet",
                          "selections": [
                            {
                              "kind": "Field",
                              "name": {
                                "kind": "Name",
                                "value": "value"
                              },
                              "arguments": [],
                              "directives": []
                            }
                          ]
                        }
                      },
                      {
                        "kind": "InlineFragment",
                        "typeCondition": {
                          "kind": "NamedType",
                          "name": {
                            "kind": "Name",
                            "value": "PingListResult"
                          }
                        },
                        "directives": [],
                        "selectionSet": {
                          "kind": "SelectionSet",
                          "selections": [
                            {
                              "kind": "Field",
                              "name": {
                                "kind": "Name",
                                "value": "list"
                              },
                              "arguments": [],
                              "directives": []
                            }
                          ]
                        }
                      },
                      {
                        "kind": "InlineFragment",
                        "typeCondition": {
                          "kind": "NamedType",
                          "name": {
                            "kind": "Name",
                            "value": "ErrorResult"
                          }
                        },
                        "directives": [],
                        "selectionSet": {
                          "kind": "SelectionSet",
                          "selections": [
                            {
                              "kind": "Field",
                              "name": {
                                "kind": "Name",
                                "value": "message"
                              },
                              "arguments": [],
                              "directives": []
                            }
                          ]
                        }
                      }
                    ]
                  }
                },
                {
                  "kind": "Field",
                  "alias": {
                    "kind": "Name",
                    "value": "Ping2"
                  },
                  "name": {
                    "kind": "Name",
                    "value": "ping"
                  },
                  "arguments": [
                    {
                      "kind": "Argument",
                      "name": {
                        "kind": "Name",
                        "value": "action"
                      },
                      "value": {
                        "kind": "EnumValue",
                        "value": "LAST"
                      }
                    }
                  ],
                  "directives": [],
                  "selectionSet": {
                    "kind": "SelectionSet",
                    "selections": [
                      {
                        "kind": "InlineFragment",
                        "typeCondition": {
                          "kind": "NamedType",
                          "name": {
                            "kind": "Name",
                            "value": "PingStringResult"
                          }
                        },
                        "directives": [],
                        "selectionSet": {
                          "kind": "SelectionSet",
                          "selections": [
                            {
                              "kind": "Field",
                              "name": {
                                "kind": "Name",
                                "value": "value"
                              },
                              "arguments": [],
                              "directives": []
                            }
                          ]
                        }
                      },
                      {
                        "kind": "InlineFragment",
                        "typeCondition": {
                          "kind": "NamedType",
                          "name": {
                            "kind": "Name",
                            "value": "PingListResult"
                          }
                        },
                        "directives": [],
                        "selectionSet": {
                          "kind": "SelectionSet",
                          "selections": [
                            {
                              "kind": "Field",
                              "name": {
                                "kind": "Name",
                                "value": "list"
                              },
                              "arguments": [],
                              "directives": []
                            }
                          ]
                        }
                      },
                      {
                        "kind": "InlineFragment",
                        "typeCondition": {
                          "kind": "NamedType",
                          "name": {
                            "kind": "Name",
                            "value": "ErrorResult"
                          }
                        },
                        "directives": [],
                        "selectionSet": {
                          "kind": "SelectionSet",
                          "selections": [
                            {
                              "kind": "Field",
                              "name": {
                                "kind": "Name",
                                "value": "message"
                              },
                              "arguments": [],
                              "directives": []
                            }
                          ]
                        }
                      }
                    ]
                  }
                }
              ]
            }
          }
        ],
        "__key": 743869514
      },
      "variables": {
        "action": "ALL"
      },
      "operationName": "query",
      "context": {
        "url": "http://localhost:4000/graphql",
        "preferGetMethod": false,
        "suspense": false,
        "requestPolicy": "cache-and-network",
        "meta": {
          "cacheOutcome": "hit"
        }
      }
    },
    "data": {
      "__typename": "Query",
      "Ping1": {
        "__typename": "PingListResult",
        "list": [
          "World",
          "foobar",
          "wibble",
          "wobble",
          "Running mutation",
          "Running mutation"
        ]
      },
      "Ping2": {
        "__typename": "PingStringResult",
        "value": "Hello wobble"
      }
    },
    "stale": true
  },
  "mutations": {},
  "subscriptions": []
}
```

</details>

**Comment by kitten** [comment] 2020-10-05 16:10
This is likely expected behavior. I can see you posted a result console output (btw, please use spoilers or stringify that GraphQL document please if it's too long 😅 )

It says: `"stale": true`

This indicates that `cache-and-network` is indeed working and a network request is sent in the background. You should check your network tab or `urql-devtools` to confirm that. There's some info on this here: https://formidable.com/open-source/urql/docs/basics/queries/#request-policies

**Comment by JohnAtFenestra** [comment] 2020-10-05 16:14
Thanks but that was the point - there was no network request. 

Sorry about the extra length - couldn't figure out what would be needed<g>

**Comment by JohnAtFenestra** [comment] 2020-10-05 16:19
Modified query with console logging

```javascript
export async function runSuperPingQuery(action = "ALL") {
  console.log("Running query")
  const result = await adapter.query(query, {
    action
  })
  console.log("Query completed")
  return result
}
```
Screenshot of developer tools

![URQL-CacheAndNetworkNotSendingToNetwork](https://user-images.githubusercontent.com/619697/95105357-0aa8d600-0705-11eb-8f02-c7b3066f4608.png)

**Comment by JohnAtFenestra** [comment] 2020-10-05 16:27
Okay. Very weird. I made a change which forced a full reload and now everything is working correctly.

Might be due to this being a PWA and the service worker not updating correctly.

Sorry to bother you.

**Comment by kitten** [comment] 2020-10-05 16:30
Oh ok, awesome! Let's still keep this in mind and let me know whether you have a hunch that this is an edge case that isn't working correctly on our end 🤔 🙌

**Comment by JohnAtFenestra** [comment] 2020-10-05 16:40
The problem reappear but then is working correctly again. Must be a specific order of events that's triggering it. I'm debugging optimistic updates after a mutation (essential for our offline support) and there must be something about the exact order that's triggering it.

This is a pure test application (nothing proprietary) so if I can reliably replicate the issue I can put the source somewhere if you want.

**Comment by kitten** [comment] 2020-10-05 16:51
It may be an edge case here: https://github.com/FormidableLabs/urql/blob/8e7fc5ce1451b24f569343011da717362c1ba3f0/exchanges/graphcache/src/cacheExchange.ts#L118

Can you add the `debugExchange` from `@urql/core` _before_ the `offlineExchange`, reproduce this, and post the results please? If we can identify whether the `cache-and-network` request has gone out that'd help.

Basically what I'm assuming is that your mutation comes in, the optimistic update starts, the query is updated (`cache-first`) and then the mutation actually completes from a network end (which also updates), which should re-trigger the query as `cache-and-network` but maybe doesn't.

**Comment by JohnAtFenestra** [comment] 2020-10-05 16:52
Absolutely. I'll post the results in a little bit once I set it up. It does have the interesting problem that once it stops hitting the network I can't get it to hit the network no matter what I do - except purging the cache in localStorage.

**Comment by kitten** [comment] 2020-10-05 16:53
@JohnAtFenestra question, does this only happen when the optimistic mutation is done but the mutation request hasn't settled (e.g. you're testing in offline)? Because in that case Graphcache will actively block the network request.

**Comment by JohnAtFenestra** [comment] 2020-10-05 16:57
I haven't gotten to offline testing yet. I'm working through making sure that the mutations are functioning as expected in online mode and I hit this.

Log attached. Looks like the debugExchange thinks that the query is being fired off, but there is no network activity.

[localhost-1601916890155.log](https://github.com/FormidableLabs/urql/files/5328869/localhost-1601916890155.log)

**Comment by kitten** [comment] 2020-10-05 16:59
@JohnAtFenestra Ok, maybe it's that logic misfiring though 🤔 That's definitely something we should investigate if that turns out to have a consistent trigger. I can't unfortunately recognise anything in the logs; I'd need to see `operation.context.requestPolicy`, sorry 😓

**Comment by JohnAtFenestra** [comment] 2020-10-05 17:07
Took a bit but here's the entire dump of the four console lines in question.
[FullLog.log](https://github.com/FormidableLabs/urql/files/5328937/FullLog.log)

**Comment by kitten** [comment] 2020-10-05 17:14
That's very interesting... I do see the `network-only` request in there, but I don't see the mutations, so I can't be sure. However, I also see a `teardown`, which is curious since we're clearly interested in more results here.

**But**, I looked through our conversation and saw this code snippet again:

```js
export async function runSuperPingQuery(action = "ALL") {
  console.log("Running query")
  const result = await adapter.query(query, {
    action
  })
  console.log("Query completed")
  return result
}
```

Which programmatically executes a query. That's interesting because this will get a _single_ result and then give that to you, so `cache-and-network` will not give you a network result and will act like `cache-first`. However it will still dispatch a `network-only` request.

The problem here is though that if you use `client.query` with `toPromise` (the usual programmatic flow) then internally you'll immediately see a `teardown` after a query result, which is expected. This means that the `Client` in `urql` will recognise that nothing's actively looking at these queries anymore and _won't_ dispatch the `cache-and-network` network request. This also matches log.

Does that sound like a reasonable conclusion?

**Comment by JohnAtFenestra** [comment] 2020-10-05 17:28
Could be. I'm still feeling through the differences between URQL and AppSync. However, the issue I have is that no matter how many times I re-run the query and no matter what I do to the browser, the only thing which triggers the network operation is to clear the cache.

So, are you saying there is a preferred method to use client.query which would trigger the network portion of the operation and that .toPromise is what is aborting it?

I'm quite willing to restructure the code to work with the URQL workflow.

**Comment by JohnAtFenestra** [comment] 2020-10-05 18:01
I noticed there was a push earlier today to fix a `stale` flag issue. I've noticed that `stale` never seems to switch from `true` to `false`. I wonder if what I need to do here is check the `stale` flag and online state. If I am online and the `stale` flag is `true` then I need to wait for the second response. I could use a subscription, but there are reasons to prefer explicit control over query refreshes. 

It would be good to know if there is a way to make `client.query()` work under `cache-and-network` without using a subscription.

**Comment by kitten** [comment] 2020-10-05 20:49
So, let me unroll this a litte; the preferred method is to always use the bindings for React, Preact, or Svelte basically. Failing that it very much depends on what you're doing. If you need to observe a query, then what you're looking for are the stream primitives.

Then regarding `client.query().toPromise()`. That method is for sending one-off queries, so that means that `cache-and-network` is invalid basically. It doesn't make sense because it asks for up to two results, the cached result and an update. This means that a promise can't represent this result and so the second possible result is always lost.

The `stale` flag also won't switch because of this. You're only getting one result as long as it's a promise because it's not a full subscription.

Basically this is all documented here, in the Main Concepts section in general: https://formidable.com/open-source/urql/docs/concepts/stream-patterns/
The `teardown` events specifically are described here: https://formidable.com/open-source/urql/docs/concepts/philosophy/#declarative-queries

> When your app stops being interested in results for an operation (e.g. React unmounts your component) then the Client knows to teardown the operation and stops requesting new data or sending you results.

So this basically means that internally the `Client` keeps track of all queries that are _active_. This is important because you wouldn't want a leak and wouldn't want everything to always stay active.

Therefore it depends on what you're doing; why are you using `client.query` in the first place? Does it make sense to use the stream directly and keep it active for a certain amount of time, and maybe does it make sense to use one of the framework bindings instead?

The queries need a lifetime basically. As long as you're subscribed to a certain query it will be kept up-to-date and Graphcache will know when to issue new network requests, but if you use the promise primitives then all of that extra logic of issuing extra `network-only` requests isn't going to do anything, because it'll either be cancelled or the `Client` won't even send it.

If you try out the React hooks for instance you'll see that even the document cache cares about this, which comes down to `client.reexecuteOperation`. This is a frequent method used in exchanges that will re-issue an operation, e.g. for a query when it needs to be updated. However for a cache and other parts of a GraphQL client it'll never make sense to keep things up-to-date and around in memory / active at all when they aren't used.

This all doesn't apply to mutations by the way, but it does apply to queries. If you're just writing test code however, you can try to just subscribe to a query like so: https://formidable.com/open-source/urql/docs/concepts/stream-patterns/#client-query-streams

```js
import { pipe, subscribe } from 'wonka';
const QUERY = `
  query Test($id: ID!) {
    getUser(id: $id) {
      id
      name
    }
  }
`;

const { unsubscribe } = pipe(
  client.query(QUERY, { id: 'test' }),
  subscribe(result => {
    console.log(result); // { data: ... }
  })
);
```

Which will keep the query active and which will keep calling the callback until you unsubscribe.
But if you need more detailed help for what you're building then I may be able to give more specific examples.

**Comment by JohnAtFenestra** [comment] 2020-10-05 22:09
"...why are you using client.query in the first place? "

Because we are using the Quasar framework over Vue. So the React bindings don't apply. I'm essentially building a backend for the Vue frontend.

**Comment by kitten** [comment] 2020-10-05 22:26
Awesome! I have good news then; we are currently working on Vue 3 bindings https://github.com/FormidableLabs/urql/issues/1006
This shouldn't take too long but I can't name a specific date for the first release quite yet. But those will likely make it a lot easier for you

**Comment by JohnAtFenestra** [comment] 2020-10-05 22:30
I'll probably pick through your code to see what else I'm missing (I'm currently trying to figure out why the offline mutation queue isn't sending network packets on reconnect). Unfortunately, we have to be done by October 23 because of a hard operational timeline and Quasar won't be upgraded to Vue 3 for a while after that. Which is okay because this is an annual project and we're going to build off the base system for a significantly larger project.

The Authentication/Encryption layers adds a lot of complexity and interconnectivity to our application that isn't normal. It's giving me a headache.

**Comment by kitten** [comment] 2020-10-06 10:18
You can probably check our WIP PR to see whether you can already make it work: https://github.com/FormidableLabs/urql/pull/1023

It’s very rough and not done but the gist of the matter is that you’ll need to subscribe and unsubscribe according to the inputs of the query.

I’ll close this for now since the original issue is resolved but feel free to post further questions here 👍

**Closed by kitten** 2020-10-06 10:18 UTC

**Comment by JohnAtFenestra** [comment] 2020-10-06 14:30
@kitten 

I'm going to ask a question that's an offshoot of this one. I have implemented the queries using pipe instead of toPromise and they are working correctly. Now for my new problem. I have a mutation which is returning a value and is carrying out an update.

The adapter is another conversion to `toPromise`. My issue is that, while the mutation works properly in offline mode and online mode, when offline the flow never reaches the console.log I've highlighted below. Again, am I approaching this incorrectly for URQL's model?


```javascript
export async function runNormalMutation(message) {
  const mutation = `
mutation pong($message: String!) {
  pong(message: $message) {
    ...on PongIntResult {
      count
    }
    ...on ErrorResult {
      message
    }
  }
}
`
  const result = await adapter.mutate(
    mutation,
    { message },
    { additionalTypenames: ["PingStringResult", "PingListResult"] }
  )
  // When offline this never fires
  console.log({ result })
  return result
}

export const offlineSupport = {
  updates: {
    Mutation: {
      pong(result, args, cache, info) {
        const currentCachedList = cache.resolve(
          "PingListResult:listResult",
          "list"
        )
        const frozenAry = JSON.parse(JSON.stringify(currentCachedList))
        console.log({ frozenAry })
        console.log({ result })
        console.log({ args })
        cache.updateQuery({ query, variables: { action: "ALL" } }, data => {
          console.log(data)
          data.Ping1.list.push(args.message)
          return data
        })
        console.log({ cache })
        console.log({ info })
      }
    }
  },
  optimistic: {
    pong(variables, cache, info) {
      const currentList = cache.resolve("PingListResult:listResult", "list")
      return {
        __typename: "PongIntResult",
        count: currentList.length + 1
      }
    }
  },
  keys: {
    PingStringResult: () => null,
    PingListResult: data => {
      console.log(data)
      return "listResult"
    }
  }
}
```

**Comment by kitten** [comment] 2020-10-06 17:09
@JohnAtFenestra that sounds about right 👍 mutations that are optimistic are expected to be implemented as “fire-and-forget” calls; so the result isn’t guaranteed to come back if you’re offline and instead the mutation is queued up in the background and retried once you’re back online (dependent on the `storage`’s `onOnline` method)

So that’s correct. If you’re building an actual app you’d probably use it for non-consequential updates and use optimistic updates where you can’t guarantee that they’ll always be 100% reflected as you don’t know when they’ll actually be sent off.
