### ISSUE TITLE
(next-urql) useQuery SSR requests run sequentially (sync) instead of in parallel (async)

### ISSUE THREAD

**Issue by danielzlotnik** [FormidableLabs/urql#2255] opened 2022-02-07 13:21 UTC
Not sure if it's a bug or an improvement suggestion, or if it should be here or under [react-ssr-prepass](https://github.com/FormidableLabs/react-ssr-prepass).

Decided to go with a bug since the behaviour is significantly different between SSR and client-side rendering.

**urql version & exchanges:**
```
    "@urql/core": "^2.4.1",
    "next": "12.0.10",
    "next-urql": "^3.3.2",
    "urql": "^2.1.3",
    "@urql/devtools": "^2.0.3",
```

**Steps to reproduce**
1. Run multiple queries within the same component using the `useQuery` hook.
```
function Example() {
  const client = useClient();

  client.subscribeToDebugTarget(event => {
    if (event.type === 'fetchRequest') {
      console.log(`fetch request ${event.operation.variables.countryCode} - ${event.timestamp}`);
    }
    if (event.type === 'fetchSuccess') {
      console.log(`fetch success ${event.operation.variables.countryCode} - ${event.timestamp}`);
    }
  });

  const [{ data: deData }] = useQuery({
    query: COUNTRY_QUERY,
    variables: {
      countryCode: 'DE',
    },
  });
  
  const [{ data: frData }] = useQuery({
    query: COUNTRY_QUERY,
    variables: {
      countryCode: 'FR',
    },
  });

  return (
    <>
      <div>{deData?.country.name}</div>
      <div>{frData?.country?.name}</div>
    </>
  );
}

export default withUrqlClient(
  ssrExchange => ({
    url: 'https://countries.trevorblades.com/',
    exchanges: [devtoolsExchange, dedupExchange, cacheExchange, ssrExchange, fetchExchange],
  }),
  { ssr: true }
)(Example);
``` 

**Expected behavior**
Queries should run in parallel on both server and client.

**Actual behavior**
Queries run sequentially on the server, causing a significant performance impact:
```
fetch request DE - 1644229728289
--- 178 ms
fetch success DE - 1644229728467
--- next request only starts once the previous one is done (synchronous)
fetch request FR - 1644229728469
--- 117 ms
fetch success FR - 1644229728586
```

They do run in parallel on the browser though.

**Comment by JoviDeCroock** [comment] 2022-02-07 13:23
This is inherent to `suspense` and `react-ssr-prepass` so not much we can do about 😅 generally in Relay/... they use colocated Fragments and gather the general data-requirements on the top-level. A normalized cache is able to derive subsets of that data in-turn.

**Comment by kitten** [comment] 2022-02-07 13:47
Closing for now, since this is expected behaviour ✌️ Feel free to keep replying though. I'm also happy to convert it to a discussion.

To reiterate, Suspense stops a component from rendering. The same will happen when Suspense is used on the client-side. Generally, that's one of the reasons why queries should be composed and merged. From a different perspective though, if you know that two GraphQL queries will always load at the same time, why would we send two queries? The general idea here is that they can be combined.

One way to deal with this is to make fragments that specify data requirements and compose them both into the query, the other obviously being generated queries and manual composition

**Closed by kitten** 2022-02-07 13:47 UTC

**Comment by danielzlotnik** [comment] 2022-02-07 14:45
Thanks for the lightning-fast replies @JoviDeCroock & @kitten ! :)

The above example is indeed not great, the real use case is 2 different queries (sometimes from 2 different GQL servers so merging is not an option).

Not familiar enough with the internals of `react-ssr-prepass` to start a practical discussion, but theoretically - would it be possible to run all data-fetching hooks (within a component) in parallel and suspend the component rendering until all are resolved?

Meaning, is it just too much of an effort for something that can be worked around (by only having a single useQuery per component) or is it impossible / wrong by design?

**Comment by kitten** [comment] 2022-02-07 14:51
It's impossible by design. Suspense assumes that everything below it will render assuming the data is present, hence its pattern of interrupting the flow of rendering. Only one thing can throw a promise at a time, afterwards rendering can continue.

> sometimes from 2 different GQL servers so merging is not an option

It's important to note here that my answer in this is a little too consistent but... 😅 GraphQL allows components to define their data requirements that a remote or local schema may then fulfill.
We haven't quite explored the case of allowing schema stitching on the frontend with something like GraphQL Mesh. However, while you have this limitation of two APIs that's technically artificial and counter to what GraphQL is good at.

If you're querying from two APIs you may have UI business logic that's purely responsible for handling the bridging between both schemas, so that forces you to do something in the UI that GraphQL aims to avoid: introducing data business logic in your app.

Hence, it's typically not a problem, since we're always assuming a single schema.

I'd say, you can try to prefetch the data manually somehow, but that's really the only workaround that'd do the trick here if you need SSR

**Comment by danielzlotnik** [comment] 2022-02-07 15:29
I see what you mean now.

While we do try to avoid having to stitch the 2 APIs - that is indeed occasionally done by the FE app unfortunately :)
I wouldn't expect the GQL client to be able to handle schema-stitching though, makes sense of Urql to assume a single schema.

Thanks again! 
That really helped us look at the problem from a wider perspective.
