### ISSUE TITLE
Mutations not invalidating cache when sending a mutation with data containing a hashtag (#)

### ISSUE THREAD

**Issue by FPDK** [FormidableLabs/urql#2290] opened 2022-02-19 12:11 UTC
Hi,

This issue seems to be related to https://github.com/FormidableLabs/urql/issues/195

If I send this mutation the first time, everything is OK:

```
mutation updateItem {
    updateItem(input: {
        id: "path/to/1",
        name: "URQL example #1",
        comment:"Hello world"
    }) {
        item {
            id
        }
    }}
```

But if I then change only the name to _URQL example#2_ and send the mutation again, then the old mutation is sent.

The new mutation shows up if I console.log my mutation before calling my URQL client:
```
console.log(mutation) // This outputs the new mutation (changed name)
client
            .mutation(mutation)
            .toPromise()
            .then((response) => {
...
})
```

A new mutation is sent if:
- Another property is changed as well (`name: "URQL example #2", comment: "Hello github"`)
- The content before the hashtag is changed (`name: "Something before the hashtag#and after"`)

I have set up my client as follows:
```
const client = createClient({
    url: API_GRAPHQL_URL,
    requestPolicy: "network-only",
    exchanges: [
        devtoolsExchange,
        dedupExchange,
        fetchExchange,
    ],
    fetchOptions: () => {
        return {
            credentials: "include",
            headers: {},
            cache: "no-cache",
        }
    },
})
```

My temporary fix is to always change another property in the mutation (append a space to the "comment" in the above case).

I am using urql@2.1.3 on Typescript react@17.0.2.

**Comment by JoviDeCroock** [comment] 2022-02-19 21:23
Mind making a reproduction? The client you linked is not using a cache so that could be the issue 😅

**Comment by kitten** [comment] 2022-02-21 21:53
This is technically a duplicate of https://github.com/FormidableLabs/urql/issues/1960 and we weren't too inclined to make this more complicated when this is more of an uncommon behaviour due to the lack of variables in the query. It also leads to degraded behaviour rather than straight up breakage, but we could update the regex here too

**Closed** 2022-02-23 22:36 UTC
Labels: bug 🐛
