### ISSUE TITLE
HTTPS failure with localhost + node-fetch

### ISSUE THREAD

**Issue by acao** [FormidableLabs/urql#2114] opened 2021-12-01 08:36 UTC
when making HTTPS requests while using urql in the vscode-graphql client, users are getting this FetchError:
```
OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242
```

They have found that switching from localhost to 0.0.0.0 fixes the issue

https://github.com/graphql/vscode-graphql/issues/321

urql version & exchanges:
 "@urql/core": "^2.3.5"

with node-fetch

should we use that one exchange for local development if host name is localhost?

**Steps to reproduce**

1. Install vscode-graphql
2. Attempt to make an authorized https query to a localhost endpoint. Try with 0.0.0.0 hostname to confirm it works

**Expected behavior**

Should allow a request

**Actual behavior**

(error noted above)

**Comment by JoviDeCroock** [comment] 2021-12-01 12:50
I wonder if this is caused by the issue-owner using a `http` endpoint but `vscode-graphql` using an [`https agent`](https://github.com/graphql/vscode-graphql/blob/master/src/client/network-helper.ts#L4)

**Comment by acao** [comment] 2021-12-02 08:58
@JoviDeCroock thank you, will do!

**Comment by JoviDeCroock** [comment] 2021-12-03 18:48
Fixed by https://github.com/graphql/vscode-graphql/pull/374

**Closed by JoviDeCroock** 2021-12-03 18:48 UTC
Labels: bug 🐛

**Comment by acao** [comment] 2021-12-03 20:52
Ope, sorry to leave it open, thanks y‘all!
