### ISSUE TITLE
Invoking executeMutation rapidly with no input results in incorrect return value

### ISSUE THREAD

**Issue by philostler** [FormidableLabs/urql#1622] opened 2021-05-09 00:09 UTC
I am developing a file upload React component that invokes a mutation to get a "ticket" for every uploaded file selected.

Hence when multiple files are selected the following code is executed rapidly...
```ts
const [, createOneUpload] = useUploadCreateOneUploadMutation();

<Upload
  action={async (file: File) => {
    const { data } = await createOneUpload();
    console.log("file:" + file.name + " id:" + data?.createOneUpload?.id);

    return data?.createOneUpload?.url || "";
  }}
>
```

`createOneUpload` is invoked without any parameters as we are simply asking for a unique upload object to be generated on the server.

I expected the console output to be...
```
file: File1 id:1
file: File2 id:2
```

Instead I got...
```
file: File1 id:1
file: File2 id:1
```

After debugging further in [this code](https://github.com/FormidableLabs/urql/blob/ef4b5b002d31e17d84fb41e5feb24d2200c9656f/packages/react-urql/src/hooks/useMutation.ts#L44) I could make the mutation return the expected result only when passing in dummy values to the mutation as input.

It appears that the underlaying code in urql doesn't work correctly in this scenario of passing no parameters to a mutation.

urql version & exchanges:
"urql": "2.0.2",

**Steps to reproduce**

1. Setup a mutation that takes no input but returns a unique attribute (such as `id`)
2. Invoke the mutation rapidly (within a loop would probably work)
3. Observe returned `id`

**Expected behavior**
`id` is different per invocation of the mutation

**Actual behavior**
`id` is the same per invocation of the mutation

**Comment by kitten** [comment] 2021-05-09 00:30
I'd love to discuss this a bit more! Unfortunately, I do have to preface this by saying that this is expected behaviour in that mutations must at least produce different variables to yield separate results. This is an internal limitation because it is assumed that a mutation would have different inputs at all times, e.g. if an upload is passed into multipart it'd have distinct non-keyable objects that aren't stringified but instead receive different files, or when pre-creating entities that at least an initial ID is passed. So this goes all the way down to how variables and mutations are keyed 🤔

**Comment by philostler** [comment] 2021-05-09 01:00
I understand the preface, as I was able to get this working by passing dummy unique data into the mutation. The mutation in question doesn't actually perform any file upload, I have a fully de-coupled architecture where the client requests a "ticket" from `createOneUpload` which is a freshly created `Upload` object with an attribute pointing towards a short-life S3 location to upload to.

There is nothing in the GraphQL spec (to my knowledge) that states an input to a mutation is required, so my GraphQL mutation is valid and `urql` not being able to support it is a bug in my book.  Furthermore, I'm using TS and the typings allow me to do pass nothing in without warning (although I generating the client via `graphql-codegen`).

Rather than relying on the variables, is there scope for uniquely identifying an invocation to create the expected behaviour?

**Comment by kitten** [comment] 2021-05-09 15:11
Hiya again :wave:

So, this isn't really about calling mutations without any variables, or providing differing variables, as that's all fine. We also had a thread about this a long time ago, but I can't find it anymore.

What this comes down to is that while we could support this and make this work, it wouldn't change the outcome or create a best practice scenario that you'd be happy with, with this particular use case 😅

To elaborate on this, every operation creates a key and every result is then marked with the original operation and this key, as outlined in our [Architecture docs page](https://formidable.com/open-source/urql/docs/architecture/). Mutations are a little special in that you can dispatch them multiple times, even concurrently, and they'll be let through to the `fetchExchange`, i.e. to become an API request. However, their keys may not differ which changes which results you can observe at a time.

In your case, even if we allowed these keys to change, i.e. if the mutation's key changes just because it's been dispatched repeatedly, you'd still get only the latest result, since one hook (be it for subscriptions, queries, or mutations) serves only a single result at a time. If you'd then switch to `client.mutation(...)` you'd also still run into this issue, unless you run them sequentially.

If you don't run them sequentially this leads to other questions, i.e: Why isn't the input differing if we're pre-creating multiple upload paths, e.g. by file name or by a client-side added ID? And if that's not applicable and we're running these concurrently, why wouldn't we create all these files at a time in a single mutation?

If we then lift all of these limitations and even consider all of this and create even more unique keys then it still raises the question of why we'd want to observe an unlimited amount of results for idential mutation inputs, which can be rather unreliable in the presence of retry logic, network instability and other factors; In other words, this is a conscious limitation because it only causes trouble with mutations that we'd consider to not follow best practices.

If for instance a mutation does become unique and predictable by matters of their inputs (we're not talking about predictable output, but I mean specifically predictable input to a single output) then this problem goes away and enables the exchange pipeline to be more effectively used for your specific mutations.

**Comment by kitten** [comment] 2021-05-13 11:31
Closing this for now, since we consider this expected behaviour. However we did have more details on why this is in #1639 :v:

**Closed by kitten** 2021-05-13 11:31 UTC

**Comment by philostler** [comment] 2021-05-15 10:26
Thank you for your full-bodied reply to my question. I see the challenges, and on balance, as my situation is WIP I believe this line is most true for me....

> ...why wouldn't we create all these files at a time in a single mutation?

This is highly likely to be true in my case and will solve the problem outright.

I still believe this limitation should be documented more clearly, but this issue now also exists as guidance for others encountering this limitation.

Thanks, and thank you for the continuously impressive `urql` library. The best GraphQL client my far IMO ATM.
